### ISSUE TITLE
map_traces_locally fails with "ImportError: No module named appengine.api"

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1211]
I'm just going to remove the import, it's not used yet.

```
Traceback (most recent call last):
  File "./map_traces_locally", line 11, in <module>
    from perf_insights import map_traces_locally
  File "/usr/local/google/ssd/repos/catapult/perf_insights/perf_insights/map_traces_locally.py", line 12, in <module>
    from perf_insights import map_runner
  File "/usr/local/google/ssd/repos/catapult/perf_insights/perf_insights/map_runner.py", line 10, in <module>
  File "/usr/local/google/ssd/repos/catapult/perf_insights/perf_insights/map_single_trace.py", line 13, in <module>
    import cloudstorage as gcs
  File "/usr/local/google/ssd/repos/catapult/perf_insights/third_party/cloudstorage/__init__.py", line 20, in <module>
    from .api_utils import RetryParams
  File "/usr/local/google/ssd/repos/catapult/perf_insights/third_party/cloudstorage/api_utils.py", line 44, in <module>
    from google.appengine.api import app_identity
ImportError: No module named appengine.api
```

**Comment by dstockwell** [comment]
Fixed in https://github.com/catapult-project/catapult/commit/a88919765cece3301aa0da9e8cecdc6f8a7e8ea5
