### ISSUE TITLE
PRESUBMIT crashes when the bug field is not correct.

### ISSUE THREAD

**Issue by vmpstr** [catapult-project/catapult#1238]
I had a patch with a description and a line that said

BUG=catapult:1232

Then I made some changes and tried to upload, presubmit didn't like that:

$ git cl upload
Using 50% similarity for rename/copy detection. Override with --similarity.
Running presubmit upload checks ...
Traceback (most recent call last):
  File "/path/to/depot_tools/git_cl.py", line 3564, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/path/to/depot_tools/git_cl.py", line 3546, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/path/to/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/path/to/depot_tools/git_cl.py", line 2381, in CMDupload
    change=change)
  File "/path/to/depot_tools/git_cl.py", line 1087, in RunHook
    rietveld_obj=self.RpcServer())
  File "/path/to/depot_tools/presubmit_support.py", line 1476, in DoPresubmitChecks
    results += executer.ExecPresubmitScript(presubmit_script, filename)
  File "/path/to/depot_tools/presubmit_support.py", line 1393, in ExecPresubmitScript
    result = eval(function_name + '(*__args)', context)
  File "<string>", line 1, in <module>
  File "<string>", line 77, in CheckChangeOnUpload
  File "<string>", line 68, in CheckChange
TypeError: '_PresubmitError' object is not iterable
Sending crash report ...
  args: ['/path/to/depot_tools/git_cl.py', 'upload']
  cwd: /path/to/catapult
  exception: '_PresubmitError' object is not iterable
  host: awesomehost
  stack:   File "/path/to/depot_t
  user: vmpstr
  version: 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2

Changing the BUG to be in BUG=#1234 format fixes stuff. 

For the record,
'File "<string>", line 68, in CheckChange' in PRESUBMIT.py, line 68 is:
results += CheckChangeLogBug(input_api, output_api)

**Comment by vmpstr** [comment]
@natduca, fyi

**Comment by anniesullie** [comment]
Sorry about this! Broke this check in recent refactors. Fix in https://codereview.chromium.org/1284213002/
