### ISSUE TITLE
map_traces_locally fails and hangs on trace

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1241]
To reproduce:
- Get the latest version of https://github.com/natduca/measurmt-traces.git
- Copy measurmt-traces/desktop/slow-reports/trace-e50482337d92936f.gz to its own directory
- Run
  ./map_traces_locally -j 8 THE_DIRECTORY/ ../perf_insights_examples/map_process_count.html
The error below is printed and the process hangs and must be killed manually. Using -j 1 causes the error but the process doesn't hang.

The error:

Fatal error in Full GC promotion failed
Allocation failed - process out of memory

Traceback (most recent call last):
  File "./map_traces_locally", line 14, in <module>
    sys.exit(map_traces_locally.Main(sys.argv))
  File "/Users/beaudoin/trace-viewer/catapult/perf_insights/perf_insights/map_traces_locally.py", line 53, in Main
    results = runner.Run(jobs=args.jobs, output_formatters=[output_formatter])
  File "/Users/beaudoin/trace-viewer/catapult/perf_insights/perf_insights/map_runner.py", line 56, in Run
    self._WorkLoop()
  File "/Users/beaudoin/trace-viewer/catapult/perf_insights/perf_insights/map_runner.py", line 51, in _WorkLoop
    self._ProcessTrace(self._work_queue.get())
  File "/Users/beaudoin/trace-viewer/catapult/perf_insights/perf_insights/map_runner.py", line 41, in _ProcessTrace
    os.path.abspath(self._map_file))
  File "/Users/beaudoin/trace-viewer/catapult/perf_insights/perf_insights/map_single_trace.py", line 90, in MapSingleTrace
    sys.stderr.write(res.stdout.read())

**Comment by philippebeaudoin** [comment]
Paging @natduca

**Comment by natduca** [comment]
@dstockwell any ideas?

**Comment by natduca** [comment]
@philippebeaudoin should we p1 this?

**Comment by dstockwell** [comment]
I guess I expected that MapSingleTrace would be doing exception handing and returning a failure in this case. In this case I think we end up dropping the thread that's running the task and never calling _work_queue.task_done()

**Comment by natduca** [comment]
Ah, I get it! I think its probably right that the runner should assume that mapping will succeed, meaning we shoudl patch 

@philippebeaudoin mind trying a patch to catch the exception in map_trace_locally.py and push a FailureValue to the reuslts object containing the exception? I can do it, but not till Friday due to #1219 and #1237

**Comment by philippebeaudoin** [comment]
Picking it up, good opportunity to flex my mad python skillz!
