### ISSUE TITLE
Error when viewing /alerts?triaged=true: unexepected None

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1377]
To reproduce, navigate to https://chromeperf.appspot.com/alerts?triaged=true
```
I'm getting the following stack trace:
Traceback (most recent call last):
  File "dashboard/alerts.py", line 49, in get
    'stoppage_alert_list': json.dumps(StoppageAlertDicts(stoppage_alerts)),
  File "dashboard/alerts.py", line 122, in StoppageAlertDicts
    return [_GetStoppageAlertDict(a) for a in stoppage_alerts]
  File "dashboard/alerts.py", line 152, in _GetStoppageAlertDict
    'last_row_date': str(stoppage_alert_entity.last_row_date.date()),
AttributeError: 'NoneType' object has no attribute 'date'
```
Related file: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/alerts.py

**Comment by qyearsley** [comment]
In the currently-deployed version (including that CL), this appears to be fixed (the page is loading).

However, the underlying problem is that stoppage alerts aren't migrated by migrate_test_names. Will file a new bug for that.
