### ISSUE TITLE
Perf Dashboard: internal server error during new bug creation

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1570]
Chrome version: 47.0.2522.0 (Windows)
URL: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmdCLqAkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6fmz4AgM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6YeytAsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6Yu68QoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmcTxvwsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmeDhuAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmYKhsAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmcTtoQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmef6oQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6ffj7AgM

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
No js errors, but there were server errors

Please describe the problem:
Repro steps:
1) Fill in the checkbox for all 10 alerts
2) Click the Triage button
3) Click the New Bug button

Issue - I saw this internal server error:
Internal Server Error

The server has either erred or is incapable of performing the requested operation.

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/file_bug.py", line 38, in post
    self.get()
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/oauth2client/oauth2client/appengine.py", line 731, in check_oauth
    resp = method(request_handler, *args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/file_bug.py", line 72, in get
    self._CreateBug(summary, description, labels, keys)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/file_bug.py", line 143, in _CreateBug
    bisect_result = auto_bisect.StartNewBisectForBug(bug_id)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/auto_bisect.py", line 108, in StartNewBisectForBug
    bisect_result = start_try_job.PerformBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/start_try_job.py", line 631, in PerformBisect
    return PerformBuildbucketBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/start_try_job.py", line 812, in PerformBuildbucketBisect
    _MakeBuildbucketBisectJob(bisect_job))
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/start_try_job.py", line 783, in _MakeBuildbucketBisectJob
    'Recipe is only implemented for tests run on chromium.perf '
InvalidInputError: Recipe is only implemented for tests run on chromium.perf (and chromium.perf.fyi).
```

The good news is that [crbug 538642](http://crbug.com/538642) was created, but the server error I guess prevented the dashboard UI from showing me that new bug creation notification.

**Comment by anniesullie** [comment]
@ro-berto @vuppalapu

**Comment by qyearsley** [comment]
Clearly bugs should be able to be filed and the bug creation notification should be shown regardless of what `auto_bisect` does or whether it raises an error
.
This CL should fix this particular case: https://codereview.chromium.org/1369923007

**Comment by qyearsley** [comment]
Fix confirmed now :-)
