### ISSUE TITLE
Perf Dashboard: 

### ISSUE THREAD

**Issue by phoglund** [catapult-project/catapult#1578]
Chrome version: 45.0.2454.101 (Linux)
URL: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2enYvwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6bbAvAsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmfOKsQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2e6buwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2enYvwsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2YD-rAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6d-4swsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6eeaswkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2dqwqgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2drapgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2dqBtwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmembtwsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2YS6rgoM

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):

Please describe the problem:

From this regression on the WebRTC bots: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2enYvwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6bbAvAsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmfOKsQoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2e6buwkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2enYvwsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2YD-rAoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6d-4swsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA6eeaswkM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2dqwqgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2drapgoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2dqBtwoM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAmembtwsM,agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDA2YS6rgoM

I do this:
1) Click Triage -> File a bug
2) Fill in bug and click submit
3) The following internal server error occurs:

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/file_bug.py", line 38, in post
    self.get()
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/oauth2client/oauth2client/appengine.py", line 731, in check_oauth
    resp = method(request_handler, *args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/file_bug.py", line 72, in get
    self._CreateBug(summary, description, labels, keys)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/file_bug.py", line 143, in _CreateBug
    bisect_result = auto_bisect.StartNewBisectForBug(bug_id)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/auto_bisect.py", line 108, in StartNewBisectForBug
    bisect_result = start_try_job.PerformBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/start_try_job.py", line 631, in PerformBisect
    return PerformBuildbucketBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/start_try_job.py", line 812, in PerformBuildbucketBisect
    _MakeBuildbucketBisectJob(bisect_job))
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-5a9889ef.387521459367675102/dashboard/start_try_job.py", line 783, in _MakeBuildbucketBisectJob
    'Recipe is only implemented for tests run on chromium.perf '
InvalidInputError: Recipe is only implemented for tests run on chromium.perf (and chromium.perf.fyi).

**Comment by qyearsley** [comment]
Same as #1570.
