### ISSUE TITLE
The /auto_bisect cron job is failing.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1661]
Pretty straight-forward failure:

```
Traceback (most recent call last):
  File ".../dashboard/auto_bisect.py", line 66, in _RestartFailedBisectJobs
    _RestartBisect(job)
  File ".../dashboard/auto_bisect.py", line 90, in _RestartBisect
    start_try_job.PerformBisect(bisect_job)
  File ".../dashboard/start_try_job.py", line 636, in PerformBisect
    return PerformBuildbucketBisect(bisect_job)
  File ".../dashboard/start_try_job.py", line 817, in PerformBuildbucketBisect
    _MakeBuildbucketBisectJob(bisect_job))
  File ".../dashboard/start_try_job.py", line 798, in _MakeBuildbucketBisectJob
    bisect_director=GetBisectDirectorForTester(config['recipe_tester_name']),
KeyError: 'recipe_tester_name'
```

See [start_try_job.py:790](https://github.com/catapult-project/catapult/blob/61253f34072fc3903354831ba5dc82403f227bcf/dashboard/dashboard/start_try_job.py#L790). The config parameter "recipe_tester_name" either be considered optional and a default provided, or an error should be thrown earlier.

**Comment by qyearsley** [comment]
So "recipe_tester_name" should be required for bisect jobs that are started with buildbucket, I believe. Not sure why there are some jobs with configs that are missing this property for which use_buildbucket is True.

Uploaded CL to make this a non-fatal error in auto_bisect, and hopefully find out more about what bisect jobs are failing to auto-restart: https://codereview.chromium.org/1419783006

**Comment by anniesullie** [comment]
I'm still seeing this:

```
2015-10-26 07:36:00.963
Missing "recipe_tester_name".
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-1239e34d.388037660149947742/dashboard/auto_bisect.py", line 36, in get
    self.post()
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-1239e34d.388037660149947742/dashboard/auto_bisect.py", line 44, in post
    _RestartFailedBisectJobs()
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-1239e34d.388037660149947742/dashboard/auto_bisect.py", line 66, in _RestartFailedBisectJobs
    _RestartBisect(job)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-1239e34d.388037660149947742/dashboard/auto_bisect.py", line 90, in _RestartBisect
    start_try_job.PerformBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-1239e34d.388037660149947742/dashboard/start_try_job.py", line 618, in PerformBisect
    return PerformBuildbucketBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-1239e34d.388037660149947742/dashboard/start_try_job.py", line 804, in PerformBuildbucketBisect
    _MakeBuildbucketBisectJob(bisect_job))
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-1239e34d.388037660149947742/dashboard/start_try_job.py", line 782, in _MakeBuildbucketBisectJob
    raise ValueError('Missing "recipe_tester_name".')
ValueError: Missing "recipe_tester_name".
```

**Comment by qyearsley** [comment]
Just looked at the config of the bisect job for which this is occuring:
```
{
  "max_time_minutes": "20", 
  "metric": "typed-array-set-from-typed/typed-array-set-from-typed", 
  "bug_id": "527054", 
  "truncate_percent": "25", 
  "target_arch": "ia32", 
  "repeat_count": "10", 
  "good_revision": "334860", 
  "bisect_mode": "mean", 
  "builder_type": "perf", 
  "command": "tools/perf/run_benchmark -v --browser=android-chromium --output-format=buildbot --also-run-disabled-tests blink_perf.bindings", 
  "bad_revision": "346444"
}
```

Looks like this was meant to be a non-recipe bisect but for some reason the TryJob got use_buildbucket set to True.

My CL above was intended to make auto_bisect fail silently and log an error with the config in this case (but I put the try/except block in the wrong place :-/)

I suspect that this may be a one-off thing which may not affect future bisect jobs, so I uploaded another CL which should make auto_bisect actually ignore this type of error: https://codereview.chromium.org/1425503003

**Comment by qyearsley** [comment]
The only errors recently are:

1. The API call urlfetch.Fetch() took too long to respond and was cancelled.
2. Request was aborted after waiting too long to attempt to service your request.

These are both relatively infrequent errors, and different from the original issue.
