### ISSUE TITLE
Dashboard's /add_point/ crashes when 'charts' is empty.

### ISSUE THREAD

**Issue by ppiet** [catapult-project/catapult#1733]
```
INFO     2015-11-06 13:56:50,694 module.py:786] default: "POST /add_point HTTP/1.1" 500 2909
INFO     2015-11-06 13:57:02,917 add_point.py:140] Received data: {u'chart_data': {u'charts': {}, u'benchmark_name': u'mojo_benchmarks', u'format_version': u'1.0'}, u'bot': u'mojobot', u'versions': {u'mojo': u'cebd9191638f94f2d07da7a81970fcae92fd708a'}, u'buildnumber': 12, u'buildername': u'mojobuilder', u'master': u'mojomaster', u'supplemental': {}, u'point_id': u'5325', u'masterid': u'mojomaster'}
ERROR    2015-11-06 13:57:02,918 api_server.py:272] Exception while handling service_name: "taskqueue"
method: "BulkAdd"
request: ""
request_id: "lkquxAGGKD"

Traceback (most recent call last):
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 247, in _handle_POST
    api_response = _execute_request(request).Encode()
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 189, in _execute_request
    make_request()
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 181, in make_request
    request_id)
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/api/apiproxy_stub.py", line 131, in MakeSyncCall
    method(request, response)
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 2207, in _Dynamic_BulkAdd
    assert request.add_request_size(), 'taskqueue should prevent empty requests'
AssertionError: taskqueue should prevent empty requests

ERROR    2015-11-06 13:57:02,919 webapp2.py:1553] AssertionError('taskqueue should prevent empty requests',)
Traceback (most recent call last):
  File "/usr/local/google/home/ppi/Install/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/usr/local/google/home/ppi/Install/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/usr/local/google/home/ppi/Install/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/usr/local/google/home/ppi/Install/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/usr/local/google/home/ppi/Install/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/usr/local/google/home/ppi/Install/google_appengine/lib/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/tmp/deploy-YlJ0CQ/dashboard/add_point.py", line 154, in post
    _AddTasksAsync(data)
  File "/tmp/deploy-YlJ0CQ/dashboard/add_point.py", line 245, in _AddTasksAsync
    queue.add_async(task_list).get_result()
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/api/taskqueue/taskqueue.py", line 1948, in ResultHook
    rpc.check_success()
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/api/apiproxy_rpc.py", line 157, in _WaitImpl
    self.request, self.response)
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 201, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/usr/local/google/home/ppi/Install/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 235, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception())
RuntimeError: AssertionError('taskqueue should prevent empty requests',)
```

**Comment by qyearsley** [comment]
Fixed now. I quickly tried out running:

```
import urllib
import urllib2

URL = 'http://localhost:8080/add_point'
DATA = {
    'master': 'ChromiumPerf',
    'bot': 'win7',
    'point_id': '12345',
    'chart_data': {
        'benchmark_name': 'my_benchmark',
        'charts': {}
    }
}


def main():
  postdata = urllib.urlencode({'data': DATA})
  try:
    response = urllib2.urlopen(url=URL, data=postdata)
    print response.read()
  except urllib2.HTTPError as e:
    print 'HTTPError', e.reason
    print e.read()


if __name__ == '__main__':
  main()
```

Which printed
```
HTTPError Bad Request
Invalid JSON string.
```

**Comment by qyearsley** [comment]
The above change caused https://code.google.com/p/chromium/issues/detail?id=569718 -- some tests run on chromium.perf were sending empty results, and when the dashboard reports an error, the step fails and turns purple.

So we probably don't actually want to respond with an error in this case -- we probably just want to ignore it and move on and give a 200 response.
