### ISSUE TITLE
Catapult Windows Tryserver failing with 404

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1772]
Log: https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/1155/steps/Dashboard%20Dev%20Server%20Tests%20Canary/logs/stdio

This happened to me today repeatedly. It looks like the bot has __trouble downloading Chrome__:

```
Traceback (most recent call last):
  File "E:\b\build\slave\catapult\build\catapult\dashboard\bin\run_dev_server_tests", line 14, in <module>
    sys.exit(run_dev_server_tests.Main(sys.argv + ['--tests=dashboard']))
  File "E:\b\build\slave\catapult\build\catapult\catapult_build\run_dev_server_tests.py", line 233, in Main
    tmpdir, version = DownloadChrome(channel)
  File "E:\b\build\slave\catapult\build\catapult\catapult_build\run_dev_server_tests.py", line 131, in DownloadChrome
    platform_data['installer_url'], version)
  File "E:\b\build\slave\catapult\build\catapult\catapult_build\run_dev_server_tests.py", line 108, in DownloadSignedWinChrome
    local_file.write(urllib2.urlopen(url).read())
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by petrcermak** [comment]
I tried running the script locally (forcing it to download the Windows installer) and it downloaded the file (https://commondatastorage.googleapis.com/chrome-signed/desktop-W15K3Y/46.0.2490.86/win/46.0.2490.86_chrome_installer.exe) without any issues, so it's probably a trybot issue.

@nedn, @anniesullie: Any idea who to route this to?

**Comment by petrcermak** [comment]
Correction: I forgot to set the canary channel. The __file indeed doesn't exist__ (https://commondatastorage.googleapis.com/chrome-signed/desktop-W15K3Y/48.0.2562.1/win/48.0.2562.1_chrome_installer.exe).

**Comment by petrcermak** [comment]
This is almost certainly a __Chromium issue__: https://code.google.com/p/chromium/issues/detail?id=554559.

Should we _temporarily disable the Windows bot_ so that we could land Catapult patches, or should we _wait_ until the Chrome canary is available for Windows again?

**Comment by nedn** [comment]
If windows bot is the only one that failing, how about just add NOTRY=true? That crbug issue is P0, so I expect it to be fixed soon-ish.

**Comment by petrcermak** [comment]
@nedn: I agree.

The issue seems to be __fixed__ now :tada::tada::tada: (I've just landed a patch through the CQ).
