### ISSUE TITLE
Catapult Windows Tryserver failing with 404 again

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1786]
_[Previous bug: #1772]_

This happens to all Catapult patches. The issue is that the bot has __trouble downloading Chrome__:

```
Traceback (most recent call last):
  File "E:\b\build\slave\catapult\build\catapult\dashboard\bin\run_dev_server_tests", line 14, in <module>
    sys.exit(run_dev_server_tests.Main(sys.argv + ['--tests=dashboard']))
  File "E:\b\build\slave\catapult\build\catapult\catapult_build\run_dev_server_tests.py", line 233, in Main
    tmpdir, version = DownloadChrome(channel)
  File "E:\b\build\slave\catapult\build\catapult\catapult_build\run_dev_server_tests.py", line 131, in DownloadChrome
    platform_data['installer_url'], version)
  File "E:\b\build\slave\catapult\build\catapult\catapult_build\run_dev_server_tests.py", line 108, in DownloadSignedWinChrome
    local_file.write(urllib2.urlopen(url).read())
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "E:\b\depot_tools\python276_bin\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

Chromium issue: https://code.google.com/p/chromium/issues/detail?id=557012

**Comment by petrcermak** [comment]
@nedn, @anniesullie: FYI

**Comment by anniesullie** [comment]
@qyearsley - can you remove the canary test for perf dashboard as a short term fix, and then reassign to me for longer term fix?

**Comment by petrcermak** [comment]
@primiano suggested _pinning_ Chrome Canary to a known version instead: https://codereview.chromium.org/1453253002

**Comment by qyearsley** [comment]
Not sure if it's necessary given the above CL, but I removed the canary test for now (https://codereview.chromium.org/1454503003/), now re-assigning to Annie

**Comment by anniesullie** [comment]
I got some resolution on the supported way to download a chrome channel prebuilt, it's automating [these instructions](https://www.chromium.org/getting-involved/download-chromium).

I have a WIP patch on this in https://codereview.chromium.org/1454333005/
