### ISSUE TITLE
Dashboard fails to updated issues for the bisect jobs triggered by rietveld

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#1831]
I think https://codereview.chromium.org/1491783002/ broke the way the contents are parsed for rietveld response. Because of this jobs triggered via rietveld are not updating issues.

Caught Exception AttributeError: content
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/clean-prasadv-e068fadc.389013049052236608/dashboard/update_bug_with_results.py", line 114, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-prasadv-e068fadc.389013049052236608/dashboard/update_bug_with_results.py", line 154, in _CheckJob
    _CheckBisectJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-prasadv-e068fadc.389013049052236608/dashboard/update_bug_with_results.py", line 269, in _CheckBisectJob
    bisect_results = _GetBisectResults(job)
  File "/base/data/home/apps/s~chromeperf/clean-prasadv-e068fadc.389013049052236608/dashboard/update_bug_with_results.py", line 308, in _GetBisectResults
    try_job_info = _ValidateRietveldResponse(response)
  File "/base/data/home/apps/s~chromeperf/clean-prasadv-e068fadc.389013049052236608/dashboard/update_bug_with_results.py", line 604, in _ValidateRietveldResponse
    issue_data = json.loads(response.content)
  File "/base/data/home/apps/s~chromeperf/clean-prasadv-e068fadc.389013049052236608/httplib2/httplib2/__init__.py", line 1671, in __getattr__
    raise AttributeError, name
AttributeError: content

**Comment by qyearsley** [comment]
Chris, can you verify whether this is fixed now?

**Comment by chrisphn** [comment]
This is fixed.  Dashboard is able to access internal and external Rietveld for the bisect job's Buildbucket info.
