### ISSUE TITLE
please_exit is flaky

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#1843]
The dev server's please_exit logic is flaky, which means that it sometimes gets into a state where KeyboardInterrupt is swallowed.

@natduca

**Comment by natduca** [comment]
Oh god. Hahaha. Hmmm.... darn python and its keyboard interruptus.

**Comment by eakuefner** [comment]
It'll look a little funny because I'm still hacking on the progress reporter stuff, but here's one from the branch, after which I can't C-c:

Now running on http://127.0.0.1:8003
/work/code/catapult/dashboard
/work/code/catapult/third_party/polymer
/work/code/catapult/third_party
/work/code/catapult/tracing
/work/code/catapult/tracing/third_party
/work/code/catapult/tracing/third_party/jszip
/work/code/catapult/tracing/third_party/gl-matrix/dist
/work/code/catapult/tracing/third_party/d3
/work/code/catapult/tracing/third_party/chai
/work/code/catapult/tracing/third_party/mocha
/work/code/catapult/perf_insights
Will run /perf_insights/test_data/googlemaps_ipc_newbinding.html
Failure while mapping /perf_insights/test_data/googlemaps_ipc_newbinding.html
Failure for job 3eed41be-b378-4995-a511-032f401a70e0 with function handle abfd5e28-7dd8-416c-b598-f057eece6f8a and trace handle /perf_insights/test_data/googlemaps_ipc_newbinding.html:
of type TraceImportError wtih description Could not open /perf_insights/test_data/googlemaps_ipc_newbinding.html. Stack:

TraceImportError: Could not open /perf_insights/test_data/googlemaps_ipc_newbinding.html
    at Object.FileURLTraceHandle.read (/perf_insights/mre/trace_handle.html:66:19)
    at eval (/work/code/catapult/perf_insights/perf_insights/mre/map_single_trace_cmdline.html:33:47)
    at Object.runAndConvertErrorsToFailures (/perf_insights/mre/map_single_trace.html:18:10)
    at Object.mapSingleTraceMain (/work/code/catapult/perf_insights/perf_insights/mre/map_single_trace_cmdline.html:28:12)
    at eval (/work/code/catapult/perf_insights/perf_insights/mre/map_single_trace_cmdline.html:52:15)
    at global.loadHTMLFile (/work/code/catapult/third_party/vinn/vinn/d8_bootstrap.js:301:5)
    at /work/code/catapult/third_party/vinn/vinn/d8_bootstrap.js:317:1
Traceback (most recent call last):
  File "/work/code/catapult/perf_insights/perf_insights/mre/threaded_work_queue.py", line 84, in _TryToRunOneTask
    task()
  File "/work/code/catapult/perf_insights/perf_insights/mre/threaded_work_queue.py", line 64, in RunTask
    cb(*args, **kwargs)
  File "/work/code/catapult/perf_insights/perf_insights/map_runner.py", line 66, in _MergeResultsToIntoMaster
    self._results.AddResults(subresults)
  File "/work/code/catapult/perf_insights/perf_insights/mre/map_results.py", line 32, in AddResults
    for key, results in results_dict.iteritems():
AttributeError: 'MapResults' object has no attribute 'iteritems'

**Comment by eakuefner** [comment]
It's _possible_ this is due to something in the branch, so I'm fine to avoid the potential wild goose chase for now until we're closer to landable.

**Comment by eakuefner** [comment]
Let's archive this.
