### ISSUE TITLE
Perf dashboard fails to add more than 6400 points in one request.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1868]
In [add_point.py](https://github.com/catapult-project/catapult/tree/master/dashboard/dashboard/add_point.py), when adding data to put in the datastore into the add_point_queue task queue, the data is broken up into groups of 64 bits and then multiple tasks are added to the queue at once.

But recently when Cluster Telemetry tried to upload data, we found out that a max of 100 tasks can be added at once to a task queue:

```
No more than 100 tasks can be added in a single call
Traceback (most recent call last):
  File ".../dashboard/add_point.py", line 155, in post
    _AddTasksAsync(data)
  File ".../dashboard/add_point.py", line 262, in _AddTasksAsync
    queue.add_async(task_list).get_result()
  File ".../google/appengine/api/taskqueue/taskqueue.py", line 1880, in add_async
    rpc)
  File ".../google/appengine/api/taskqueue/taskqueue.py", line 1983, in __AddTasks
    MAX_TASKS_PER_ADD)
TooManyTasksError: No more than 100 tasks can be added in a single call
```

The obvious fix is to add 100 tasks at a time, and make multiple calls.

**Comment by qyearsley** [comment]
CL: https://codereview.chromium.org/1558613002/

**Comment by qyearsley** [comment]
Fixed
