### ISSUE TITLE
Dashboard returns 500 for internal sheriff alerts page when logged out.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1877]
Since https://codereview.chromium.org/1550363002/, the dashboard tries to get() the sheriff info from datastore before showing alerts. But when the sheriff is marked as internal-only, when the get() is done in a request made by a logged-out user, an assertion is raised.

See: See http://crbug.com/575174

```
Traceback (most recent call last):
  File ".../dashboard/alerts.py", line 40, in get
    if sheriff_key.get() is None:
  File ".../appengine/ext/ndb/key.py", line 572, in get
    return self.get_async(**ctx_options).get_result()
  File ".../appengine/ext/ndb/tasklets.py", line 341, in get_result
    self.check_success()
  File ".../appengine/ext/ndb/tasklets.py", line 336, in check_success
    self.wait()
  File ".../appengine/ext/ndb/tasklets.py", line 320, in wait
    if not ev.run1():
  File ".../appengine/ext/ndb/eventloop.py", line 250, in run1
    delay = self.run0()
  File ".../appengine/ext/ndb/eventloop.py", line 212, in run0
    callback(*args, **kwds)
  File ".../appengine/ext/ndb/tasklets.py", line 490, in _on_future_completion
    self._help_tasklet_along(ns, ds_conn, gen, val)
  File ".../appengine/ext/ndb/tasklets.py", line 401, in _help_tasklet_along
    self.set_result(result)
  File ".../appengine/ext/ndb/tasklets.py", line 285, in set_result
    callback(*args, **kwds)
  File ".../dashboard/models/internal_only_model.py", line 26, in _post_get_hook
    assert False
AssertionError
```

Possible solution 1: `AlertsHandler.get` could call `datastore_hooks.SetSinglePrivilegedRequest()` before fetching the Sheriff, and explicitly check the user's privilege and Sheriff's internal_only property.

Possible solution 2: `AlertsHandler.get` could use a try/except block to catch the assertion error

Possible solution 3: `AlertsHandler.get` could fetch Sheriff keys and see if the requested sheriff is in the list (the number of Sheriff entities is pretty small, and requesting all sheriff keys is always fast).

@anniesullie I'm leaning towards solution 3 since it seems the simplest, any thoughts?

**Comment by qyearsley** [comment]
After http://crrev.com/1569933002, now when I navigate to https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down when logged out, I get the message 'Sheriff "WebRTC Perf Sheriff" not found.' instead of a 500.
