### ISSUE TITLE
Catapult recipe "Run SDK downloader" fails, when a request to cloud.google.com fails.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1916]
Example failed builds:
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Linux%20Tryserver/builds/1633
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Linux%20Tryserver/builds/1634

Stack:
```
Looking up path /b/build/slave/catapult/build/google_appengine
Found installed version 1.9.31
Traceback (most recent call last):
  File "/tmp/tmpaXcebb.py", line 135, in <module>
    sys.exit(main())
  File "/tmp/tmpaXcebb.py", line 131, in main
    os.path.abspath(options.dest), options.go, options.dry_run)
  File "/tmp/tmpaXcebb.py", line 89, in install_latest_gae_sdk
    url, new_version = get_latest_gae_sdk_url(name)
  File "/tmp/tmpaXcebb.py", line 36, in get_latest_gae_sdk_url
    content = urllib2.urlopen(url).read()
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

Annie notes that changing the catapult recipe to use a newer pinned version of the downloader script may help (at least with error messages). Later, this issue should be void when #1407 is fixed.

@dave-2 @anniesullie

**Comment by anniesullie** [comment]
This step is passing again, was there a fix?

**Comment by qyearsley** [comment]
Yep, https://codereview.chromium.org/1637603002/ was committed which updated the pinned version of the downloader script (which does retries).

It's still possible for it to fail again (if cloud.google.com decided to reject all requests), but this appears to be working fine now, so I'll close this issue.
