### ISSUE TITLE
Error in quick_logger: Record instance has no attribute 'id'

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2023]
After deploying the latest version of the dashboard including https://codereview.chromium.org/1661173002/ ("Add unique id to quick_log Record"), I'm seeing this stack trace in the logs:

```
Record instance has no attribute 'id'
Traceback (most recent call last):
  File "dashboard/start_try_job.py", line 107, in post
    result = self._PerformBisectStep(user)
  File "dashboard/start_try_job.py", line 156, in _PerformBisectStep
    results = PerformBisect(bisect_job)
  File "dashboard/start_try_job.py", line 615, in PerformBisect
    result = _PerformBuildbucketBisect(bisect_job)
  File "dashboard/start_try_job.py", line 829, in _PerformBuildbucketBisect
    LogBisectResult(bisect_job.bug_id, bug_comment)
  File "dashboard/start_try_job.py", line 764, in LogBisectResult
    logger.Save()
  File "google/appengine/ext/ndb/utils.py", line 197, in inner_wrapper
    return wrapped_decorator(func, args, kwds, **options)
  File "google/appengine/ext/ndb/model.py", line 3834, in transactional
    func, args, kwds, **options).get_result()
  File "google/appengine/ext/ndb/tasklets.py", line 342, in get_result
    self.check_success()
  File "google/appengine/ext/ndb/tasklets.py", line 389, in _help_tasklet_along
    value = gen.send(val)
  File "google/appengine/ext/ndb/context.py", line 1014, in transaction
    result = callback()
  File "google/appengine/ext/ndb/model.py", line 3842, in <lambda>
    return transaction_async(lambda: func(*args, **kwds), **options)
  File "dashboard/quick_logger.py", line 256, in Save
    self._MergeRecords(records, stored_records)
  File "dashboard/quick_logger.py", line 284, in _MergeRecords
    records.extend(r for r in stored_records
  File "dashboard/quick_logger.py", line 285, in <genexpr>
    if getattr(r, 'id') not in new_ids)
AttributeError: Record instance has no attribute 'id'
```

It looks like `getattr` raises an `AttributeError` if the attribute is not found and no default is provided -- it doesn't have a default of `None` like `dict.get`. We need to explicitly say to use a default of `None`.

**Comment by qyearsley** [comment]
Fixed.
