### ISSUE TITLE
web_perf TraceException unit test failures on Linux with --browser=system

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2055]
@nedn can you help triage? e.g.

  Traceback (most recent call last):
    File "/work/code/catapult/telemetry/telemetry/web_perf/smooth_gesture_util_unittest.py", line 139, in testSmoothGestureAdjusted
      self.RunMeasurement(ScrollingGestureTestMeasurement(), ps)
    File "/work/code/catapult/telemetry/telemetry/testing/page_test_test_case.py", line 70, in RunMeasurement
      story_runner.Run(measurement, ps, options, results)
    File "/work/code/catapult/telemetry/telemetry/internal/story_runner.py", line 219, in Run
      _RunStoryAndProcessErrorIfNeeded(story, results, state, test)
    File "/work/code/catapult/telemetry/telemetry/internal/story_runner.py", line 84, in _RunStoryAndProcessErrorIfNeeded
      state.RunStory(results)
    File "/work/code/catapult/telemetry/telemetry/page/shared_page_state.py", line 323, in RunStory
      self._current_page.Run(self)
    File "/work/code/catapult/telemetry/telemetry/page/__init__.py", line 83, in Run
      shared_state.page_test.WillNavigateToPage(self, current_tab)
    File "/work/code/catapult/telemetry/telemetry/web_perf/smooth_gesture_util_unittest.py", line 131, in WillNavigateToPage
      tab.browser.platform.tracing_controller.StartTracing(config)
    File "/work/code/catapult/telemetry/telemetry/core/tracing_controller.py", line 35, in StartTracing
      self._tracing_controller_backend.StartTracing(tracing_config, timeout)
    File "/work/code/catapult/telemetry/telemetry/internal/platform/tracing_controller_backend.py", line 70, in StartTracing
      self.StartAgentTracing(config, timeout)
    File "/work/code/catapult/telemetry/telemetry/internal/platform/tracing_controller_backend.py", line 115, in StartAgentTracing
      trace_event.trace_enable(self._trace_log)
    File "/work/code/catapult/tools/py_trace_event/py_trace_event/trace_event.py", line 69, in trace_enable
      return trace_event_impl.trace_enable(logfile)
    File "/work/code/catapult/tools/py_trace_event/py_trace_event/trace_event_impl/log.py", line 50, in trace_enable
      _trace_enable(log_file)
    File "/work/code/catapult/tools/py_trace_event/py_trace_event/trace_event_impl/log.py", line 39, in locked_fn
      ret = fn(*args,**kwargs)
    File "/work/code/catapult/tools/py_trace_event/py_trace_event/trace_event_impl/log.py", line 58, in _trace_enable
      raise TraceException("Tracing control not allowed in child processes.")

**Comment by eakuefner** [comment]
I figured out that the problem is that the tests in question need @decorators.Isolated. I'm uploading a patch shortly to address this.
