### ISSUE TITLE
TBMv2 breaks catapult roll: missing davclient.davclient module

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2069]
Sample roll: https://codereview.chromium.org/1738083002

Only commit in the range is https://codereview.chromium.org/1685683003

telemetry_perf_unittests are failing. Example: 
https://build.chromium.org/p/tryserver.chromium.mac/builders/mac_chromium_rel_ng/builds/186472/steps/telemetry_perf_unittests%20%28with%20patch%29%20on%20Mac-10.9/logs/stdio
```

[1/1] scripts_smoke_unittest.ScriptsSmokeTest.testRunRecordWprList failed unexpectedly 0.5888s:
  Traceback (most recent call last):
    File "/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/scripts_smoke_unittest.py", line 58, in testRunRecordWprList
      self.assertEquals(return_code, 0, stdout)
  AssertionError: 
  Traceback (most recent call last):
    <module> at tools/perf/record_wpr:21
      sys.exit(record_wpr.Main(path_util.GetPerfDir()))
    Main at third_party/catapult/telemetry/telemetry/record_wpr.py:262
      _PrintAllBenchmarks(base_dir, sys.stderr)
    _PrintAllBenchmarks at third_party/catapult/telemetry/telemetry/record_wpr.py:100
      _PrintAllImpl(_GetSubclasses(base_dir, benchmark.Benchmark), 'benchmarks',
    _GetSubclasses at third_party/catapult/telemetry/telemetry/record_wpr.py:78
      index_by_class_name=True)
    Cacher at third_party/catapult/telemetry/telemetry/decorators.py:34
      cacher.__cache[key] = obj(*args, **kwargs)
    DiscoverClasses at third_party/catapult/telemetry/telemetry/core/discover.py:79
      modules = DiscoverModules(start_dir, top_level_dir, pattern)
    Cacher at third_party/catapult/telemetry/telemetry/decorators.py:34
      cacher.__cache[key] = obj(*args, **kwargs)
    DiscoverModules at third_party/catapult/telemetry/telemetry/core/discover.py:48
      module = __import__(module_name, fromlist=[True])
  ImportError: No module named davclient.davclient
  
  Locals:
    _               : []
    dir_path        : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/third_party/davclient'
    filename        : 'davclient.py'
    filenames       : ['__init__.py', 'davclient.py', 'README.chromium']
    module          : <module 'profile_creators.update_remote_extensions' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/update_remote_extensions.pyc'>
    module_name     : 'third_party.davclient.davclient'
    module_rel_path : 'third_party/davclient/davclient.py'
    modules         : [<module 'ct_benchmarks_util' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/ct_benchmarks_util.pyc'>, <module 'fetch_benchmark_deps' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/fetch_benchmark_deps.pyc'>, <module 'fetch_benchmark_deps_unittest' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/fetch_benchmark_deps_unittest.pyc'>, <module 'PRESUBMIT' from '/private/var/folders/9x/6c6sv3cj4j53wzp ... safe_url_list' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/profile_safe_url_list.pyc'>, <module 'profile_creators.small_profile_extender' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/small_profile_extender.pyc'>, <module 'profile_creators.update_remote_extensions' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/update_remote_extensions.pyc'>] (truncated)
    pattern         : '*'
    start_dir       : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf'
    top_level_dir   : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf'
  
  

Retrying failed tests (attempt #2 of 3)...

[1/1] scripts_smoke_unittest.ScriptsSmokeTest.testRunRecordWprList failed unexpectedly 0.5581s:
  Traceback (most recent call last):
    File "/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/scripts_smoke_unittest.py", line 58, in testRunRecordWprList
      self.assertEquals(return_code, 0, stdout)
  AssertionError: 
  Traceback (most recent call last):
    <module> at tools/perf/record_wpr:21
      sys.exit(record_wpr.Main(path_util.GetPerfDir()))
    Main at third_party/catapult/telemetry/telemetry/record_wpr.py:262
      _PrintAllBenchmarks(base_dir, sys.stderr)
    _PrintAllBenchmarks at third_party/catapult/telemetry/telemetry/record_wpr.py:100
      _PrintAllImpl(_GetSubclasses(base_dir, benchmark.Benchmark), 'benchmarks',
    _GetSubclasses at third_party/catapult/telemetry/telemetry/record_wpr.py:78
      index_by_class_name=True)
    Cacher at third_party/catapult/telemetry/telemetry/decorators.py:34
      cacher.__cache[key] = obj(*args, **kwargs)
    DiscoverClasses at third_party/catapult/telemetry/telemetry/core/discover.py:79
      modules = DiscoverModules(start_dir, top_level_dir, pattern)
    Cacher at third_party/catapult/telemetry/telemetry/decorators.py:34
      cacher.__cache[key] = obj(*args, **kwargs)
    DiscoverModules at third_party/catapult/telemetry/telemetry/core/discover.py:48
      module = __import__(module_name, fromlist=[True])
  ImportError: No module named davclient.davclient
  
  Locals:
    _               : []
    dir_path        : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/third_party/davclient'
    filename        : 'davclient.py'
    filenames       : ['__init__.py', 'davclient.py', 'README.chromium']
    module          : <module 'profile_creators.update_remote_extensions' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/update_remote_extensions.pyc'>
    module_name     : 'third_party.davclient.davclient'
    module_rel_path : 'third_party/davclient/davclient.py'
    modules         : [<module 'ct_benchmarks_util' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/ct_benchmarks_util.pyc'>, <module 'fetch_benchmark_deps' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/fetch_benchmark_deps.pyc'>, <module 'fetch_benchmark_deps_unittest' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/fetch_benchmark_deps_unittest.pyc'>, <module 'PRESUBMIT' from '/private/var/folders/9x/6c6sv3cj4j53wzp ... safe_url_list' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/profile_safe_url_list.pyc'>, <module 'profile_creators.small_profile_extender' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/small_profile_extender.pyc'>, <module 'profile_creators.update_remote_extensions' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/update_remote_extensions.pyc'>] (truncated)
    pattern         : '*'
    start_dir       : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf'
    top_level_dir   : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf'
  
  

Retrying failed tests (attempt #3 of 3)...

[1/1] scripts_smoke_unittest.ScriptsSmokeTest.testRunRecordWprList failed unexpectedly 0.5474s:
  Traceback (most recent call last):
    File "/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/scripts_smoke_unittest.py", line 58, in testRunRecordWprList
      self.assertEquals(return_code, 0, stdout)
  AssertionError: 
  Traceback (most recent call last):
    <module> at tools/perf/record_wpr:21
      sys.exit(record_wpr.Main(path_util.GetPerfDir()))
    Main at third_party/catapult/telemetry/telemetry/record_wpr.py:262
      _PrintAllBenchmarks(base_dir, sys.stderr)
    _PrintAllBenchmarks at third_party/catapult/telemetry/telemetry/record_wpr.py:100
      _PrintAllImpl(_GetSubclasses(base_dir, benchmark.Benchmark), 'benchmarks',
    _GetSubclasses at third_party/catapult/telemetry/telemetry/record_wpr.py:78
      index_by_class_name=True)
    Cacher at third_party/catapult/telemetry/telemetry/decorators.py:34
      cacher.__cache[key] = obj(*args, **kwargs)
    DiscoverClasses at third_party/catapult/telemetry/telemetry/core/discover.py:79
      modules = DiscoverModules(start_dir, top_level_dir, pattern)
    Cacher at third_party/catapult/telemetry/telemetry/decorators.py:34
      cacher.__cache[key] = obj(*args, **kwargs)
    DiscoverModules at third_party/catapult/telemetry/telemetry/core/discover.py:48
      module = __import__(module_name, fromlist=[True])
  ImportError: No module named davclient.davclient
  
  Locals:
    _               : []
    dir_path        : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/third_party/davclient'
    filename        : 'davclient.py'
    filenames       : ['__init__.py', 'davclient.py', 'README.chromium']
    module          : <module 'profile_creators.update_remote_extensions' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/update_remote_extensions.pyc'>
    module_name     : 'third_party.davclient.davclient'
    module_rel_path : 'third_party/davclient/davclient.py'
    modules         : [<module 'ct_benchmarks_util' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/ct_benchmarks_util.pyc'>, <module 'fetch_benchmark_deps' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/fetch_benchmark_deps.pyc'>, <module 'fetch_benchmark_deps_unittest' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/fetch_benchmark_deps_unittest.pyc'>, <module 'PRESUBMIT' from '/private/var/folders/9x/6c6sv3cj4j53wzp ... safe_url_list' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/profile_safe_url_list.pyc'>, <module 'profile_creators.small_profile_extender' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/small_profile_extender.pyc'>, <module 'profile_creators.update_remote_extensions' from '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf/profile_creators/update_remote_extensions.pyc'>] (truncated)
    pattern         : '*'
    start_dir       : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf'
    top_level_dir   : '/private/var/folders/9x/6c6sv3cj4j53wzpzthbp4ksm0000gm/T/runjKKUvd/tools/perf'
  
```

**Comment by eakuefner** [comment]
Ned has graciously volunteered to help out with this.

**Comment by eakuefner** [comment]
For posterity, the issue here is that I modified sys.path in `tracing_project.py` and that broke Telemetry. The core bug here is the long-standing issue that the directory structure of tools/perf is bizarre.
