### ISSUE TITLE
500 error on /buildbucket_job_status for some job ID numbers.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2130]
I saw this in the logs today.

To reproduce:
Navigate to: https://chromeperf.appspot.com/buildbucket_job_status/9018879393839358624

```
Traceback (most recent call last):
  File ".../dashboard/buildbucket_job_status.py", line 41, in get
    'original_response': original_status,
  File ".../dashboard/request_handler.py", line 41, in RenderHtml
    self.response.out.write(template.render(template_values))
  File ".../third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File ".../dashboard/templates/buildbucket_job_status.html", line 24, in top-level template code
    Test: {{build.parameters.properties.bisect_config.command}}
  File ".../third_party/jinja2-2.6/jinja2/environment.py", line 372, in getattr
    return getattr(obj, attribute)
UndefinedError: 'dict object' has no attribute 'bisect_config'
```

Other buildbucket job status pages work.
https://chromeperf.appspot.com/buildbucket_job_status/9018467993988906976

@ro-berto, do you think this is maybe because the job is not a bisect job? In this case, we could add a little more error handling in here.

**Comment by anniesullie** [comment]
I'm going to close this since we'll likely open a new issue if this happens again.
