### ISSUE TITLE
TypeError in dashboard/add_point.py (when invalid chartjson is sent)

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2141]
Today I saw a new error in the logs; this is probably a bug that we didn't see manifest before because nobody sent data malformed in this particular way.

```
Traceback (most recent call last):
  File ".../dashboard/add_point.py", line 144, in post
    data = _DashboardJsonToRawRows(data)
  File ".../dashboard/add_point.py", line 220, in _DashboardJsonToRawRows
    if not (math.isnan(specific_vals['value']) or
TypeError: a float is required
```

https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/add_point.py#L220

This was triggered by a request with this data:

```json
{
  "versions": {
    "cros_version": "51.8061.0.0", 
    "chrome_version": "51.0.2672.0"
  }, 
  "point_id": 26720000806100000, 
  "bot": "...", 
  "chart_data": {
    "charts": {
      "...PSon": {
        "udp_rx": {
          "units": "Mbps", 
          "type": "scalar", 
          "value": [
            26.73, 
            26.73, 
            26.73
          ], 
          "improvement_direction": "up"
        }
      }, 
    }, 
    "format_version": "1.0", 
    "benchmark_name": "network_WiFi_Perf"
  }, 
  "master": "...WiFi", 
  "supplemental": {
    "default_rev": "chrome_version", 
  }
}
```

The specific problem is that instead of "scalar", the type should be "list_of_scalar_values".

The dashboard should return a 400 with an error message instead of 500, and the sender of data should be informed.

**Comment by qyearsley** [comment]
Haven't seen this error in the logs since the fix.
