### ISSUE TITLE
DeadlineExceededError in /group_report

### ISSUE THREAD

**Issue by chrisphn** [catapult-project/catapult#2161]
Hm, is it me or is `/group_report` page is taking longer to load than usual?  In some cases it just times out.

Seen error in log:

```
Traceback (most recent call last):
  File ".../dashboard/group_report.py", line 57, in post
    self._ShowAlertsForKeys(keys)
  File ".../dashboard/group_report.py", line 157, in _ShowAlertsForKeys
    self._ShowAlerts(anomalies)
  File ".../dashboard/group_report.py", line 177, in _ShowAlerts
    'subtests': _GetSubTestsForAlerts(alert_dicts),
  File ".../dashboard/group_report.py", line 206, in _GetSubTestsForAlerts
    testsuite, [bot_name])
  File ".../dashboard/list_tests.py", line 90, in GetSubTests
    _SubTestsDict(deprecated_sub_test_paths, True))
  File ".../dashboard/list_tests.py", line 137, in _SubTestsDict
    sub_test_paths = _SubPaths(paths, name)
  File ".../dashboard/list_tests.py", line 147, in _SubPaths
    if '/' in p and p.split('/')[0] == first_part]
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.

```

**Comment by qyearsley** [comment]
Probably depends on the specific tests for the alert keys you're looking at -- do you still have the particular URL where you were seeing time outs?

**Comment by chrisphn** [comment]
Lost it; will post it when I run into it again.
