### ISSUE TITLE
Can't load traceviewer in node on a non-executable filesystem

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#2170]
Sorry, this is a bit of a weird one. Maybe wontfix?

    events.js:154
          throw er; // Unhandled 'error' event
          ^
    TypeError: invalid data
        at WriteStream.Socket.write (net.js:623:11)
        at Object.execFileSync (child_process.js:487:20)
        at Object.module.exports.getSourcePathsForProject (/var/host/media/removable/sdcard/local/repos/erlnmyr/node_modules/traceviewer/catapult_build/node_bootstrap.js:62:41)
        at Object.<anonymous> (/var/host/media/removable/sdcard/local/repos/erlnmyr/node_modules/traceviewer/tracing/tracing/index.js:15:20)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)

Probably related to:

    var sourcePathsString = child_process.execFileSync(
        path.join(catapultBuildPath, 'print_project_info'),
        ['--headless-test-module-filenames', projectName]);

**Comment by natduca** [comment]
Hmmm probably a bug of us still having a hacky node modules architecture.

In the short term, maybe we could try figuring out the path to python and add that as a prefix? Or /usr/bin/env python ...?
