### ISSUE TITLE
map_traces.Main() always fails

### ISSUE THREAD

**Issue by bashi** [catapult-project/catapult#2177]
`results` is a list, not an instance which has `failures` attribute.

<pre>
Traceback (most recent call last):
  File "/usr/local/google/home/bashi/catapult/perf_insights/bin/map_traces", line 14, in <module>
    sys.exit(map_traces.Main(sys.argv))
  File "/usr/local/google/home/bashi/catapult/perf_insights/perf_insights/map_traces.py", line 88, in Main
    if not results.failures:
AttributeError: 'list' object has no attribute 'failures'
</pre>

**Comment by natduca** [comment]
@eakuefner

**Comment by eakuefner** [comment]
@simonhatch

**Comment by eakuefner** [comment]
Looks like bashi has the fix in https://codereview.chromium.org/1831253002

**Comment by eakuefner** [comment]
This is **done**. Thanks @bashi!
