### ISSUE TITLE
Error when collecting trace data

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2292]
Platform: windows
Log: https://build.chromium.org/p/tryserver.chromium.perf/builders/winx64_10_perf_cq/builds/148/steps/v8.infinite_scroll-ignition/logs/stdio

(ERROR) 2016-04-28 13:22:32,638 tracing_controller_backend.CollectAgentTraceData:247  Error when deleting c:\users\chrome~2\appdata\local\temp\tmp4mgatc, will try again at exit.
Traceback (most recent call last):
  File "C:\b\build\slave\winx64_10_perf_cq\build\src\third_party\catapult\telemetry\telemetry\internal\platform\tracing_controller_backend.py", line 243, in CollectAgentTraceData
    os.remove(self._trace_log)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\chrome~2\\appdata\\local\\temp\\tmp4mgatc'

**Comment by nedn** [comment]
Randy: can you take a look?

**Comment by randalnephew** [comment]
I think this is caused by a race condition in windows where we close a fd for a file, but windows doesn't fully release it by the time we attempt to delete it. The file gets deleted at exit though:
https://build.chromium.org/p/tryserver.chromium.perf/builders/winx64_10_perf_cq/builds/418/steps/system_health.common_desktop/logs/stdio

(ERROR) 2016-08-16 18:56:33,641 tracing_controller_backend.CollectAgentTraceData:275  Error when deleting c:\users\chrome~2\appdata\local\temp\tmpnqttob, will try again at exit.
Traceback (most recent call last):
  File "C:\b\c\b\winx64_10_perf_cq\src\third_party\catapult\telemetry\telemetry\internal\platform\tracing_controller_backend.py", line 271, in CollectAgentTraceData
    os.remove(self._trace_log)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\chrome~2\\appdata\\local\\temp\\tmpnqttob'
...
(INFO) 2016-08-16 18:57:55,467 atexit_with_log._wrapped_function:10  Try running <function DeleteAtExit at 0x368E7DB0>
(INFO) 2016-08-16 18:57:55,467 atexit_with_log._wrapped_function:12  Did run <function DeleteAtExit at 0x368E7DB0>
