### ISSUE TITLE
Fail to import after tracing some websites

### ISSUE THREAD

**Issue by wangxianzhu** [catapult-project/catapult#2328]
1. Open http://www.theatlantic.com/business/archive/2014/04/americas-rebel-band-of-custom-bike-builders/360058/
2. Open another tab, chrome://tracing
3. Record, Frame Viewer
4. Switch to Tab 1 and interact with the web page for several seconds
5. Switch to Tab 2, press stop

Expected: trace is successfully imported
Actual: it stuck for about 1 minute, then showed an error:
"Error: Couldn't create an importer for the provided eventData.
    at Object.createImporter_ (chrome://tracing/tracing.js:655:3342)
    at Object.createImports (chrome://tracing/tracing.js:650:21)
    at Object.run (chrome://tracing/tracing.js:1388:13)
    at runAnother (chrome://tracing/tracing.js:1400:136)
    at runTask (chrome://tracing/tracing.js:1363:57)
    at processIdleWork (chrome://tracing/tracing.js:1369:116)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:1357:81)", source: chrome://tracing/tracing.js (1400)

**Comment by wangxianzhu** [comment]
Some corrections:
1.1 scroll the page down nearly to the end to show the comments

**Comment by wangxianzhu** [comment]
Sometimes I get this error instead:

RangeError: Inflated gzip data too long to fit into a string (577949648).
    at Function.GzipImporter.inflateGzipData_ (chrome://tracing/tracing.js:49977:13)
    at Object.extractSubtraces (chrome://tracing/tracing.js:50035:36)
    at Object.createImports (chrome://tracing/tracing.js:7615:40)
    at Object.run (chrome://tracing/tracing.js:16310:21)
    at runAnother (chrome://tracing/tracing.js:16403:29)
    at runTask (chrome://tracing/tracing.js:16121:21)
    at processIdleWork (chrome://tracing/tracing.js:16165:7)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:16101:7)", source: chrome://tracing/tracing.js (16406)

**Comment by primiano** [comment]
@petrcermak can you take a look to this?
This seems a widespread problem and recently regressed. I got the same in canary.
See also crbug.com/630965 and crbug.com/623945

**Comment by primiano** [comment]
Failing trace https://drive.google.com/corp/drive/u/0/folders/0B03kdrYCBrmSM3hnNjZZX2VyM28

**Comment by petrcermak** [comment]
This is a __duplicate__ of #2378.

@primiano: The trace you attached is simply too big to import at the moment: _"Inflated gzip data too long to fit into a string (852714493)."_ The only thing you can do is to make it smaller, e.g. using your script in http://crbug.com/630965.
