### ISSUE TITLE
Perf dashboard stores bug_data.Bug with key 'monorail:v1'

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2359]
We get occasional `/auto_triage` errors with this stack:

```
05:28:43.698
invalid literal for int() with base 10: 'monorail:v1' (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-5ad75bb2.392931395757053443/dashboard/auto_triage.py", line 63, in post
    bug_id = int(self.request.get('bug_id'))
ValueError: invalid literal for int() with base 10: 'monorail:v1
```

Looking into this further, we actually do have a bug_data.Bug entity in our datastore with id `monorail:v1`. This is incorrect, as our entity should always be storing the chromium issue id. It looks like they are coming from monorail service: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/file_bug.py#L135

We should handle this on our end, but it seems there's occasional problems with monorail API?

**Comment by anniesullie** [comment]
Timestamp on the most recent issue which was created this way is `datetime.datetime(2016, 5, 17, 12, 38, 42, 674870)` if it helps with debugging on the monorail side.

**Comment by eakuefner** [comment]
We can maybe retry here, or throw an explicit client-side error, and not store this garbage in the datastore.

**Comment by benshayden** [comment]
Deleted the offending Bug entity.
Archiving.
