### ISSUE TITLE
Exception getting 'status' key in update_bug_with_results

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2393]
From the logs:
```
URL being requested: GET https://cr-buildbucket.appspot.com/_ah/api/buildbucket/v1/builds/9010530735067536496?alt=json (/base/data/home/apps/s~chromeperf/dev-sullivan-e2dfabbd.393325447350298804/apiclient/googleapiclient/discovery.py:765)


Caught Exception KeyError: 'status' (/base/data/home/apps/s~chromeperf/dev-sullivan-e2dfabbd.393325447350298804/dashboard/update_bug_with_results.py:92)
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-e2dfabbd.393325447350298804/dashboard/update_bug_with_results.py", line 89, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-e2dfabbd.393325447350298804/dashboard/update_bug_with_results.py", line 130, in _CheckJob
    _CheckFYIBisectJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-e2dfabbd.393325447350298804/dashboard/update_bug_with_results.py", line 155, in _CheckFYIBisectJob
    _PostResult(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-e2dfabbd.393325447350298804/dashboard/update_bug_with_results.py", line 203, in _PostResult
    comment = bisect_report.GetReport(job)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-e2dfabbd.393325447350298804/dashboard/bisect_report.py", line 99, in GetReport
    report = _BISECT_REPORT_TEMPLATE % results_data
KeyError: 'status'
```

`results_data` is set in two places. This still seems error-prone to me, as we had to fix a similar problem in #2317.
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/update_bug_with_results.py#L397
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/post_bisect_results.py#L85

@vuppalapu can you take a look?

@Apeliotes @dave-2 @eakuefner @ro-berto

**Comment by vuppalapu** [comment]
The main reason for the results_data to be None is because uploading bisect results failed on linux fyi bot 
https://build.chromium.org/p/tryserver.chromium.perf/builders/linux_fyi_perf_bisect/builds/501/steps/Post%20bisect%20results/logs/json.output
This has started on 06/07 i.e., yesterday. results upload on other bots seems to be fine.

Firstly, I'm going to raise an alert in dashboard for FYI for the bisect job which is finished (Completed successfully) but failed to get the results data.

Secondly, we need to figure-out why the authentication failed on linux_fyi_perf_bisect bot.

**Comment by vuppalapu** [comment]
Filed crbug.com/618051 for tracking authentication issue.

**Comment by Apeliotes** [comment]
Is there more work to be done here?

**Comment by vuppalapu** [comment]
Yes this is done.
