### ISSUE TITLE
Bad error message when "gathering standard output" on Android

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2445]
When there are failures on Android we get the unhelpful error message:

```
(ERROR) 2016-06-28 20:31:57,875 exceptions.__init__:71  Problem when trying to gather standard output: 'NoneType' object has no attribute 'splitlines'
```

The error itself is harmless, but still distracting while reading logs.

**Comment by perezju** [comment]
I'll also add here this other unhelpful error message here, since both can be easily fixed probably in the same CL. This one happens when trying to get the browser log.

```
(INFO) 2016-06-28 20:31:57,876 browser.DumpStateUponFailure:333  ********************* BROWSER LOG *********************
(ERROR) 2016-06-28 20:31:57,876 browser.DumpStateUponFailure:337  Failed to get browser log:
Traceback (most recent call last):
  File "/b/build/slave/perf-monochrome-n-phone/build/src/third_party/catapult/telemetry/telemetry/internal/browser/browser.py", line 335, in DumpStateUponFailure
    logging.info(self.GetLogFileContents())
  File "/b/build/slave/perf-monochrome-n-phone/build/src/third_party/catapult/telemetry/telemetry/internal/browser/browser.py", line 276, in GetLogFileContents
    return self._browser_backend.GetLogFileContents()
  File "/b/build/slave/perf-monochrome-n-phone/build/src/third_party/catapult/telemetry/telemetry/internal/backends/browser_backend.py", line 43, in GetLogFileContents
    with file(self.log_file_path) as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
(INFO) 2016-06-28 20:31:57,876 browser.DumpStateUponFailure:338  ***************** END OF BROWSER LOG ******************
```
