### ISSUE TITLE
StartBisectJob tests failing flakily on Mac.

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2464]
We're getting StartBisectJob tests that seem to fail flakily on the Catapult CQ; it's not the same test every time but they do appear to be related to interaction with the Monorail API in the code, which I think is maybe inadequately mocked. Here are a couple example stack traces; see https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Mac%20Tryserver?numbuilds=100 for more:

```
[578/657] start_try_job_test.StartBisectTest.testPerformBisectWithArchive failed unexpectedly:
  Service account credentials not found.
  <HttpError 404 when requesting https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues/12345/comments?alt=json&sendEmail=true returned "Not Found">
  argument of type 'NoneType' is not iterable
  Traceback (most recent call last):
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
      rv = self.handle_exception(request, response, e)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
      rv = self.router.dispatch(request, response)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
      return route.handler_adapter(request, response)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
      return handler.dispatch()
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
      return self.handle_exception(e, self.app.debug)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
      return method(*args, **kwargs)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/start_try_job.py", line 116, in post
      result = self._PerformBisectStep(user)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/start_try_job.py", line 165, in _PerformBisectStep
      results = PerformBisect(bisect_job)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/start_try_job.py", line 636, in PerformBisect
      issue_tracker.AddBugComment(bisect_job.bug_id, comment)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/issue_tracker_service.py", line 82, in AddBugComment
      return self._MakeCommentRequest(bug_id, body)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/issue_tracker_service.py", line 112, in _MakeCommentRequest
      if retry and 'The user does not exist' in reason:
  TypeError: argument of type 'NoneType' is not iterable
  Traceback (most recent call last):
    File "/b/build/slave/catapult/build/catapult/third_party/mock/mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/start_try_job_test.py", line 923, in testPerformBisectWithArchive
      response = self.testapp.post('/start_try_job', query_parameters)
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 371, in post
      content_type=content_type)
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 736, in _gen_request
      expect_errors=expect_errors)
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 632, in do_request
      self._check_status(status, res)
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 664, in _check_status
      res)
  AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/start_try_job)
  500 Internal Server Error
  
  The server has either erred or is incapable of performing the requested operation.
```

```
[148/657] auto_triage_test.AutoTriageTest.testPost_AllAnomaliesRecovered_AddsComment failed unexpectedly:
  name: monorail  version: v1
  Traceback (most recent call last):
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
      rv = self.handle_exception(request, response, e)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
      rv = self.router.dispatch(request, response)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
      return route.handler_adapter(request, response)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
      return handler.dispatch()
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
      return self.handle_exception(e, self.app.debug)
    File "/b/build/slave/catapult/build/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
      return method(*args, **kwargs)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/auto_triage.py", line 64, in post
      TriageBugs.UpdateRecoveredBugs(bug_id)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/auto_triage.py", line 145, in UpdateRecoveredBugs
      cls._CommentOnRecoveredBug(bug_id)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/auto_triage.py", line 158, in _CommentOnRecoveredBug
      additional_credentials=utils.ServiceAccountCredentials())
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/issue_tracker_service.py", line 42, in __init__
      http=self._http)
    File "/b/build/slave/catapult/build/google_appengine/lib/oauth2client/oauth2client/util.py", line 137, in positional_wrapper
      return wrapped(*args, **kwargs)
    File "/b/build/slave/catapult/build/catapult/third_party/apiclient/googleapiclient/discovery.py", line 200, in build
      version))
  UnknownApiNameOrVersion: name: monorail  version: v1
  Traceback (most recent call last):
    File "/b/build/slave/catapult/build/catapult/third_party/mock/mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/auto_triage_test.py", line 153, in testPost_AllAnomaliesRecovered_AddsComment
      self.ExecuteTaskQueueTasks('/auto_triage', auto_triage._TASK_QUEUE_NAME)
    File "/b/build/slave/catapult/build/catapult/dashboard/dashboard/testing_common.py", line 79, in ExecuteTaskQueueTasks
      handler_name, urllib.unquote_plus(base64.b64decode(task['body'])))
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 371, in post
      content_type=content_type)
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 736, in _gen_request
      expect_errors=expect_errors)
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 632, in do_request
      self._check_status(status, res)
    File "/b/build/slave/catapult/build/catapult/third_party/webtest/webtest/app.py", line 664, in _check_status
      res)
  AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/auto_triage)
  500 Internal Server Error
  
  The server has either erred or is incapable of performing the requested operation.
```

@anniesullie @Apeliotes @ro-berto @vuppalapu

**Comment by anniesullie** [comment]
I'll take a look at this, it could be related to my recent CL https://codereview.chromium.org/2140703002/

**Comment by eakuefner** [comment]
Thanks Annie! It does look like the tests might have started flaking out on patchset 1 of your CL.

**Comment by anniesullie** [comment]
Wow, putting an `assert False` in the codepaths that should never be called finds 14 places missing mocks. Working on a fix now.

**Comment by anniesullie** [comment]
https://codereview.chromium.org/2134383002 should fix this.

**Comment by anniesullie** [comment]
There was a second fix needed: https://codereview.chromium.org/2141983002/ should finish off the flakiness.

**Comment by anniesullie** [comment]
This is now **fixed**.
