### ISSUE TITLE
Missing parameter "id" error in update_bug_with_results when checking FYI jobs

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2631]
We are getting alerts about UpdateBugWithResults custom metric not being set. I looked at go/chromeperf-logs and it seems like `job.buildbucket_job_id` is not set for some buildbucket jobs. @vuppalapu is this expected? Should we just work around it not being set, or is it a symptom of a larger problem?

```
Caught Exception TypeError: Missing required parameter "id" (/base/data/home/apps/s~chromeperf/dev-sullivan-24590f06.394783778579408071/dashboard/update_bug_with_results.py:110)
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-24590f06.394783778579408071/dashboard/update_bug_with_results.py", line 107, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-24590f06.394783778579408071/dashboard/update_bug_with_results.py", line 154, in _CheckJob
    _CheckFYIBisectJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-24590f06.394783778579408071/dashboard/update_bug_with_results.py", line 191, in _CheckFYIBisectJob
    job_info = buildbucket_service.GetJobStatus(job.buildbucket_job_id)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-24590f06.394783778579408071/dashboard/buildbucket_service.py", line 76, in GetJobStatus
    request = service.get(id=job_id)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-24590f06.394783778579408071/apiclient/googleapiclient/discovery.py", line 634, in method
    raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "id"
```

**Comment by vuppalapu** [comment]
I noticed that there are some stale tryjob entities that are created with default configs but never triggered a bisect job, I cleaned up the datastore by deleting such entities and also uploaded a CL to check before processing FYI jobs for bug update.
https://codereview.chromium.org/2227773004/
