### ISSUE TITLE
bot_update failing on Windows

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2693]
PSA: I think I just broke `bot_update` on Windows, with some stuff I'm trying in https://codereview.chromium.org/1887323002. Long story short, I managed to get `npm install` to run (yay!) but it left behind files with paths too long to be deleted by the `git clean -dff` command that `bot_update` runs.

So someone needs to SSH into `build78-b1` and delete `catapult_base\bin\node`.

Long term I'd like to ask two questions:

1. How do I get SSH access to these bots so that I can fix these types of issues on my own? and
2. What would be the correct process for setting `git config --global core.longpaths true` on the Windows bots? Do we need to ask troopers to do this for us?

The error text, for reference, looks like this:

```
===Running git.bat clean -dff (attempt #5)===
In directory: C:\b\build\slave\catapult\build\catapult
Traceback (most recent call last):
  File "C:\b\build\scripts\slave\.recipe_deps\depot_tools\recipe_modules\bot_update\resources\bot_update.py", line 1807, in <module>
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/fstream-npm/node_modules/fstream-ignore/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match': Filename too long
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/init-package-json/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match': Filename too long
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/.npmignore': Filename too long
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/.travis.yml': Filename too long
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/node-gyp/node_modules/path-array/node_modules/array-index/node_modules/es6-symbol/node_modules/es5-ext/.lintignore': Filename too long
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/read-package-json/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match': Filename too long
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/.npmignore': Filename too long
warning: Could not stat path 'catapult_base/catapult_base/bin/node/npm_win_AMD64_0fdeec4c78abe528af760a5e9d8e0998a2dc77eb/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-license-ids/spdx-license-ids.json': Filename too long
===Failed in 0.0 mins===

Emitting flag file at C:\b\build\slave\catapult\build\update.flag
    sys.exit(main())
  File "C:\b\build\scripts\slave\.recipe_deps\depot_tools\recipe_modules\bot_update\resources\bot_update.py", line 1781, in main
    step_text)
  File "C:\b\build\scripts\slave\.recipe_deps\depot_tools\recipe_modules\bot_update\resources\bot_update.py", line 1658, in checkout
    gclient_output = ensure_checkout(**checkout_parameters)
  File "C:\b\build\scripts\slave\.recipe_deps\depot_tools\recipe_modules\bot_update\resources\bot_update.py", line 1334, in ensure_checkout
    git_ref = git_checkout(solutions, revisions, shallow, refs, git_cache_dir)
  File "C:\b\build\scripts\slave\.recipe_deps\depot_tools\recipe_modules\bot_update\resources\bot_update.py", line 1003, in git_checkout
    git('clean', '-dff', cwd=sln_dir)
  File "C:\b\build\scripts\slave\.recipe_deps\depot_tools\recipe_modules\bot_update\resources\bot_update.py", line 521, in git
    return call(*cmd, **kwargs)
  File "C:\b\build\scripts\slave\.recipe_deps\depot_tools\recipe_modules\bot_update\resources\bot_update.py", line 506, in call
    code, outval)
__main__.SubprocessFailed: git.bat clean -dff failed with code 1 in C:\b\build\slave\catapult\build\catapult after 5 attempts.
```

@dave-2 @anniesullie

**Comment by eakuefner** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=639200 to see if the troopers will get to it.

**Comment by eakuefner** [comment]
This is fixed.
