### ISSUE TITLE
telemetry.internal.results.csv_pivot_table_output_formatter_unittest.CsvPivotTableOutputFormatterTest.testMultiplePagesAndValues fails

### ISSUE THREAD

**Issue by battre** [catapult-project/catapult#2749]
telemetry.internal.results.csv_pivot_table_output_formatter_unittest.CsvPivotTableOutputFormatterTest.testMultiplePagesAndValues failed on Chrome builders:

[Log file](https://build.chromium.org/p/chromium.win/builders/Win%207%20Tests%20x64%20%281%29/builds/16411)

```
Retrying failed tests (attempt #1 of 3)...

[1/1] telemetry.internal.results.csv_pivot_table_output_formatter_unittest.CsvPivotTableOutputFormatterTest.testMultiplePagesAndValues failed unexpectedly 0.0000s:
  No traces to convert to html.
  View generated trace files online at https://cloud_storage_url/foo for page unknown
  Traceback (most recent call last):
    File "e:\b\swarm_slave\w\irl4nbto\third_party\catapult\telemetry\third_party\mock\mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "e:\b\swarm_slave\w\irl4nbto\third_party\catapult\telemetry\telemetry\internal\results\csv_pivot_table_output_formatter_unittest.py", line 110, in testMultiplePagesAndValues
      'https://cloud_storage_url/foo', '', '1'])
  AssertionError: Lists differ: ['story_set', 'http://www.bar.... != ['story_set', 'http://www.bar....
  
  First differing element 5:
  0
  1
  
    ['story_set',
     'http://www.bar.com/',
     'trace',
     'https://cloud_storage_url/foo',
     '',
  -  '0']
  ?   ^
  
  +  '1']
  ?   ^
  

Retrying failed tests (attempt #2 of 3)...
```

**Comment by eakuefner** [comment]
Looks like @nedn fixed this. Closing.
