### ISSUE TITLE
Failed steps failed run sdk downloader blocking catapult CQ

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2816]
Log:
Looking up path /b/build/slave/catapult/build/google_appengine
Found installed version 1.9.40
Traceback (most recent call last):
  File "/tmp/tmpWvuqrw.py", line 149, in <module>
    sys.exit(main())
  File "/tmp/tmpWvuqrw.py", line 145, in main
    os.path.abspath(options.dest), options.go, options.dry_run)
  File "/tmp/tmpWvuqrw.py", line 103, in install_latest_gae_sdk
    url, new_version = get_latest_gae_sdk_url(name)
  File "/tmp/tmpWvuqrw.py", line 55, in get_latest_gae_sdk_url
    url = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
step returned non-zero exit code: 1

https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Android%20Tryserver

**Comment by nedn** [comment]
This is also tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=648429

**Comment by nedn** [comment]
This is fixed.
