### ISSUE TITLE
update_bug_with_results handler throwing exception for non buildbucket jobs

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#2825]
Perf try job triggered by dashboard is not using buildbucket to trigger jobs, 
https://github.com/catapult-project/catapult/issues/2817 issue is filed to migrate this to buildbucket. But meanwhile we need to fix this error.

Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c8ca02a8.395778605894573064/dashboard/update_bug_with_results.py", line 107, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c8ca02a8.395778605894573064/dashboard/update_bug_with_results.py", line 129, in _CheckJob
    if not _IsBuildBucketJobCompleted(job):
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c8ca02a8.395778605894573064/dashboard/update_bug_with_results.py", line 417, in _IsBuildBucketJobCompleted
    job_info = buildbucket_service.GetJobStatus(job.buildbucket_job_id)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c8ca02a8.395778605894573064/dashboard/buildbucket_service.py", line 43, in GetJobStatus
    request = service.get(id=job_id)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-c8ca02a8.395778605894573064/apiclient/googleapiclient/discovery.py", line 634, in method
    raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "id"

**Comment by anniesullie** [comment]
Can this issue be closed?

**Comment by benshayden** [comment]
Archiving.
