### ISSUE TITLE
gzip inflation fails when the gunzipped file is longer than 268M characters

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3071]
Note that this is causing many failures on the waterfall for system health benchmarks. 

This can surface in benchmark runs with call stacks like:
```
TraceImportError: Invalid string length
    at Array.join (native)
    at Object.f [as string] (/b/s/w/iryelvQW/third_party/catapult/tracing/third_party/jszip/jszip.min.js:12:20494)
    at Object.c.transformTo (/b/s/w/iryelvQW/third_party/catapult/tracing/third_party/jszip/jszip.min.js:12:22247)
    at Object.c.transformTo (/b/s/w/iryelvQW/third_party/catapult/tracing/third_party/jszip/jszip.min.js:12:6414)
    at Function.GzipImporter.transformToString (/tracing/extras/importer/gzip_importer.html:141:26)
    at Function.GzipImporter.inflateGzipData_ (/tracing/extras/importer/gzip_importer.html:116:31)
    at GzipImporter.extractSubtraces (/tracing/extras/importer/gzip_importer.html:177:36)
    at Import.createImports (/tracing/importer/import.html:138:40)
    at Task.run (/tracing/base/task.html:71:21)
    at Function.Task.RunSynchronously (/tracing/base/task.html:152:25)
```

It can also fail in trace viewer when opening an interactive trace with an error message like:
```
Inflated gzip data too long to fit into a string (402408340).
```

The underlying limitation is that v8 strings can't be longer than 268435440 characters ([due to a hard-coded limit in v8](https://cs.chromium.org/chromium/src/v8/include/v8.h?sq=package:chromium&dr=C&rcl=1481199532&l=2279)).

A couple of proposed solutions: 

- We can try to figure out how to inflate gzipped traces into an `ArrayBuffer` instead of a string. `ArrayBuffers` are only limited by the memory limit of Javascript, which is configurable via a v8 flag (and therefore a Chrome browser flag). At some point, though, the importers need to be able to see the trace as a string. We could handle this by coming up with some sort of streaming import mechanism, where the importers tell us how to break apart a trace into events and we feed them one event at a time.
- We could try to reach out to the v8 team and see why v8 strings have a hard upper limit that doesn't change with the limit of how much memory v8 is allowed to use.

**Comment by zeptonaut** [comment]
Closing this as a duplicate of #2826, which @chiniforooshan is looking into
