### ISSUE TITLE
DeadineExceededError when accessing some v8 graphs

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3139]
The spinners just spin forever on [this v8 report](https://chromeperf.appspot.com/report?sid=c5287989ec59bd244ee0bf96891468e1e0f86dce1c7f1c45f51f1f4bca727493).

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/graph_json.py", line 62, in post
    self.response.out.write(GetGraphJson(**arguments))
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/graph_json.py", line 124, in GetGraphJson
    test_paths = _GetTestPathFromDict(test_path_dict)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/graph_json.py", line 493, in _GetTestPathFromDict
    sub_test_dict = _GetSubTestDict([test_path])
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/graph_json.py", line 549, in _GetSubTestDict
    subtests[test_suite_path] = list_tests.GetSubTests(test_suite, [bot_path])
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/list_tests.py", line 87, in GetSubTests
    _SubTestsDict(sub_test_paths, False),
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/list_tests.py", line 134, in _SubTestsDict
    sub_tests[name] = _SubTestsDictEntry(sub_test_paths, has_rows, deprecated)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/list_tests.py", line 149, in _SubTestsDictEntry
    'sub_tests': _SubTestsDict(sub_test_paths, deprecated)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/list_tests.py", line 132, in _SubTestsDict
    sub_test_paths = _SubPaths(paths, name)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-d49320db.398375009867083414/dashboard/list_tests.py", line 142, in _SubPaths
    if '/' in p and p.split('/')[0] == first_part]
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.
```

**Comment by dave-2** [comment]
I found so far that:

* For this particular configuration (internal.client.v8/x64/v8), there are 55,754 subtests.
* `_FetchSubTestPaths()` takes about 20s, or 1/3 of the time budget. That by itself would be okay, except:
* `_SubTestsDict()` has exponential runtime. Doubling the number of test paths multiplies its runtime by about 3.7x. (20k test paths takes 7 seconds, and 40k test paths takes 26 seconds.)
* 56k subtests would bring us just a little bit over our deadline.

**Comment by anniesullie** [comment]
Thanks, @dave-2! Closing in favor of #2887, but definitely optimizing the subtest query is what needs to happen.
