### ISSUE TITLE
Catapult roll failing

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3165]
It's been failing since this roll: https://codereview.chromium.org/2649013003/

Which has this CL:
678cfd33a `nednguyen [Telemetry] Remove labels field from story.Story constructor & labels related flags`

From the [logs](https://build.chromium.org/p/tryserver.chromium.android/builders/linux_android_rel_ng/builds/218106/steps/telemetry_perf_unittests%20%28with%20patch%29%20on%20Android/logs/stdio):
```
[302/318] page_sets.story_set_unittest.StorySetUnitTest.testSmoke failed unexpectedly 0.0153s:
  Skipping /b/swarm_slave/w/irRCEpcS/tools/perf/page_sets/partial_invalidation_cases.py: no archive data file
  Traceback (most recent call last):
    File "/b/swarm_slave/w/irRCEpcS/tools/perf/page_sets/story_set_unittest.py", line 23, in testSmoke
      self.RunSmokeTest(self.story_sets_dir, self.top_level_dir)
    File "/b/swarm_slave/w/irRCEpcS/third_party/catapult/telemetry/telemetry/testing/story_set_smoke_test.py", line 153, in RunSmokeTest
      self.CheckAttributes(story_set)
    File "/b/swarm_slave/w/irRCEpcS/third_party/catapult/telemetry/telemetry/testing/story_set_smoke_test.py", line 77, in CheckAttributes
      self.CheckAttributesOfStoryBasicAttributes(story)
    File "/b/swarm_slave/w/irRCEpcS/third_party/catapult/telemetry/telemetry/testing/story_set_smoke_test.py", line 95, in CheckAttributesOfStoryBasicAttributes
      isinstance(story.labels, set),
  AttributeError: 'PartialInvalidationCasesPage' object has no attribute 'labels'
```

@nedn can you take a look?

**Comment by nedn** [comment]
Should be fixed with https://codereview.chromium.org/2658033002/
