### ISSUE TITLE
Errors kicking bisects: "'NoneType' object has no attribute 'get'"

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3170]
In [bug 685179](http://crbug.com/685179), wangxianzhu is getting 500 errors kicking off bisects. I can kick them just fine as sullivan. Was this a transient error in buildbucket service? Or something account-specific? @simonhatch can you take a look?

```
'NoneType' object has no attribute 'get' (/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-143ba4dd.398541659830812605/dashboard/start_try_job.py", line 123, in post
    result = self._PerformBisectStep(user)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-143ba4dd.398541659830812605/dashboard/start_try_job.py", line 169, in _PerformBisectStep
    results = PerformBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-143ba4dd.398541659830812605/dashboard/start_try_job.py", line 639, in PerformBisect
    result = _PerformBuildbucketBisect(bisect_job)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-143ba4dd.398541659830812605/dashboard/start_try_job.py", line 782, in _PerformBuildbucketBisect
    _MakeBuildbucketBisectJob(bisect_job), bucket)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-143ba4dd.398541659830812605/dashboard/services/buildbucket_service.py", line 37, in PutJob
    return job.response_fields.get('id')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by simonhatch** [comment]
Obsolete with Pinpoint.
