### ISSUE TITLE
Catapult roll failing at "Switch clients to new JavaScript API (batch 5)"

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3208]
[First failing roll](https://codereview.chromium.org/2687073004/) has just [[Telemetry] Switch clients to new JavaScript API (batch 5)](https://codereview.chromium.org/2687773003) in the commit list. 

From [the log](https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Ftryserver.chromium.win%2Fwin_chromium_x64_rel_ng%2F364903%2F%2B%2Frecipes%2Fsteps%2Ftelemetry_perf_unittests__with_patch_%2F0%2Fstdout):
```
[21/26] measurements.v8_detached_context_age_in_gc_unittest.V8DetachedContextAgeInGCTests.testWithNoData failed unexpectedly 0.0020s:
  Traceback (most recent call last):
    File "e:\b\swarm_slave\w\irka5vex\tools\perf\core\path_util.pyc\..\..\measurements\v8_detached_context_age_in_gc_unittest.py", line 78, in testWithNoData
      results = _MeasureFakePage(histograms)
    File "e:\b\swarm_slave\w\irka5vex\tools\perf\core\path_util.pyc\..\..\measurements\v8_detached_context_age_in_gc_unittest.py", line 46, in _MeasureFakePage
      metric.DidNavigateToPage(page, tab)
    File "e:\b\swarm_slave\w\irka5vex\third_party\catapult\common\py_trace_event\py_trace_event\trace_event_impl\decorators.py", line 52, in traced_function
      return func(*args, **kwargs)
    File "e:\b\swarm_slave\w\irka5vex\tools\perf\core\path_util.pyc\..\..\measurements\v8_detached_context_age_in_gc.py", line 40, in DidNavigateToPage
      self._data_start = histogram_util.GetHistogram(_TYPE, _NAME, tab)
    File "e:\b\swarm_slave\w\irka5vex\third_party\catapult\telemetry\telemetry\value\histogram_util.py", line 113, in GetHistogram
      histogram_json = tab.EvaluateJavaScript2(
  AttributeError: 'FakeTab' object has no attribute 'EvaluateJavaScript2'
```

This codepath [was changed in the cl](https://codereview.chromium.org/2687773003/diff/40001/telemetry/telemetry/value/histogram_util.py)

I'm reverting for now; assigning to @perezju to reland as time permits. @nedn FYI

**Comment by perezju** [comment]
Thanks for reverting! Not sure why this wasn't caught in CQ?

**Comment by chromy** [comment]
#3149 was another case when a patch passed the CQ but stuck the auto-roller.

**Comment by chromy** [comment]
In both cases it was the same set of bots: linux_chromium_rel_ng, android_n5x_swarming_rel,  linux_chromium_rel_ng, win_chromium_x64_rel_ng and win_chromium_rel_ng is it possible/desirable to add those to the catapult CQ?

**Comment by nedn** [comment]
@dpranke

**Comment by perezju** [comment]
This is fixed now. Not sure if adding some chromium tests on the catapult CQ is being tracked elsewhere?
