### ISSUE TITLE
Catapult presubmit failing with: Unexpected keyword argument 'boot'

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3318]
A [recent CL](https://codereview.chromium.org/2724533004) removed the `boot` option from `atrace_agent.AtraceConfig` and is causing other catapult CLs to fail presubmit with:

```
** Presubmit ERRORS **
Pylint (548 files using ['--disable=cyclic-import'] on 8 cores) (22.50s) failed
************* Module telemetry.internal.platform.tracing_agent.atrace_tracing_agent
E: 32,19: Unexpected keyword argument 'boot' in constructor call (unexpected-keyword-arg)
```

Not sure how the first CL got through without triggering the same issue?

@wangzhen127 @nedn

**Comment by nedn** [comment]
The first CL probably was created before we restrict the pylintrc for telemetry (see commit logs of https://github.com/catapult-project/catapult/blob/master/telemetry/pylintrc)

**Comment by perezju** [comment]
Actually, looking at the CL description (emphasis mine):

> **Remove --boot tracing feature**
>
> The design of --boot means it misses first few seconds of bootup.
> atrace.rc isn't run for 5+ seconds after bootup, **so this hasn't been
> used** by platform developers optimizing boot, who instead use manual
> triggering of traces at startup, together with --from-file.

However the [call now failing](https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/platform/tracing_agent/atrace_tracing_agent.py#L32) was using `boot=True`:

```
self._config = atrace_agent.AtraceConfig(
    config.atrace_config.categories,
    trace_buf_size=None, kfuncs=None, app_name=app_name,
    compress_trace_data=True, from_file=True,
    device_serial_number=str(self._device), trace_time=None,
    target='android')
```

I don't know much about these things work, but sounds like the option *is* being used and the offending CL should be reverted?

**Comment by perezju** [comment]
+ @ChrisCraik who wrote the CL

Also note, the CL landed about a day ago, while the latest changes to pylintrc are over a month ago.

**Comment by nedn** [comment]
Oh, seems like in this case,  pylintrc was only invoked on change to the call sites. It worths noting that systrace's PRESUBMIT explicitly include Telemetry path for pylint but not sure why that's not working.

@dave-2

**Comment by wangzhen127** [comment]
Oh, why is Telemetry is using the boot option? I think we are safe to just remove the boot=True?

**Comment by ChrisCraik** [comment]
The boot option didn't even run before I removed it - it would throw exceptions:

```bash
catapult$ ./systrace/systrace/run_systrace.py --boot
Traceback (most recent call last):
  File "./systrace/systrace/run_systrace.py", line 181, in <module>
    main()
  File "./systrace/systrace/run_systrace.py", line 178, in main
    main_impl(sys.argv)
  File "./systrace/systrace/run_systrace.py", line 158, in main_impl
    controller.StartTracing()
  File "/media/ccraik/google4/catapult/systrace/systrace/systrace_runner.py", line 44, in StartTracing
    self._tracing_controller.StartTracing()
  File "/media/ccraik/google4/catapult/systrace/systrace/tracing_controller.py", line 146, in StartTracing
    timeout=self._controller_config.timeout):
  File "/media/ccraik/google4/catapult/common/py_utils/py_utils/__init__.py", line 85, in RunWithTimeout
    return timeout_retry.Run(func, timeout, 0, args=args)
  File "/media/ccraik/google4/catapult/systrace/systrace/../../devil/devil/utils/timeout_retry.py", line 159, in Run
    error_log_func=error_log_func)
  File "/media/ccraik/google4/catapult/systrace/systrace/../../devil/devil/utils/reraiser_thread.py", line 186, in JoinAll
    self._JoinAll(watcher, timeout)
  File "/media/ccraik/google4/catapult/systrace/systrace/../../devil/devil/utils/reraiser_thread.py", line 158, in _JoinAll
    thread.ReraiseIfException()
  File "/media/ccraik/google4/catapult/systrace/systrace/../../devil/devil/utils/reraiser_thread.py", line 81, in run
    self._ret = self._func(*self._args, **self._kwargs)
  File "/media/ccraik/google4/catapult/systrace/systrace/../../devil/devil/utils/timeout_retry.py", line 152, in <lambda>
    child_thread = reraiser_thread.ReraiserThread(lambda: func(*args, **kwargs),
  File "/media/ccraik/google4/catapult/systrace/systrace/tracing_agents/atrace_agent.py", line 302, in StartAgentTracing
    setup_args = _construct_boot_setup_command(config)
  File "/media/ccraik/google4/catapult/systrace/systrace/tracing_agents/atrace_agent.py", line 322, in _construct_boot_setup_command
    echo_args = (['echo'] + config.atrace_categories +
TypeError: can only concatenate list (not "str") to list
```

I think telemetry doesn't actually want boot=True there (or isn't actually using it).

Happy to revert the CL for now, or delete the boot=True part.

**Comment by nedn** [comment]
I removed the boot=True part. Hmhh, we do run atrace in Telemetry to produce traces like https://console.developers.google.com/m/cloudstorage/b/chrome-telemetry-output/o/trace-file-id_0-2017-02-28_00-00-09-36222.html, so it's unclear to me what happened.
