### ISSUE TITLE
systrace picks up the wrong adb

### ISSUE THREAD

**Issue by jreck** [catapult-project/catapult#3404]
systrace is picking up files named 'adb' in the current directory even if the current directory is not part of the path. This results in version mismatches between direct usage of adb and systrace's calls into adb, resulting in either large slowdowns from killing/restarting the server if the adb version differs to actual bugs & crashes.

A simple test:

$ ./systrace.py -t 1
<works fine>
$ echo hello > adb
$ adb devices
List of devices attached
HT6790200152	device
$ ./systrace.py
Traceback (most recent call last):
  File "./systrace.py", line 49, in <module>
    sys.exit(run_systrace.main())
  File "/usr/local/ssd1024/master/external/chromium-trace/catapult/systrace/systrace/run_systrace.py", line 180, in main
    main_impl(sys.argv)
  File "/usr/local/ssd1024/master/external/chromium-trace/catapult/systrace/systrace/run_systrace.py", line 143, in main_impl
    raise RuntimeError('No ADB devices connected.')
RuntimeError: No ADB devices connected.

**Comment by ChrisCraik** [comment]
Fixed with above change
