### ISSUE TITLE
Stackdriver alert: metric absence on UpdateBugWithResults

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3481]
@simonhatch @eakuefner 

The metric is ticked here, and hasn't been seen for 420 minutes: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/update_bug_with_results.py#L114

When I search the logs for errors in /update_bug_with_results, I do see many successful calls. Not sure why the metric isn't being ticked?

I also see many of this error; not sure if buildbucket is slow or we're trying to do too much in one request?
```
Caught Exception DeadlineExceededError: The API call urlfetch.Fetch() took too long to respond and was cancelled. (/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/dashboard/update_bug_with_results.py:110)
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/dashboard/update_bug_with_results.py", line 107, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/dashboard/update_bug_with_results.py", line 129, in _CheckJob
    if not _IsJobCompleted(job):
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/dashboard/update_bug_with_results.py", line 458, in _IsJobCompleted
    job_info = buildbucket_service.GetJobStatus(job.buildbucket_job_id)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/dashboard/services/buildbucket_service.py", line 44, in GetJobStatus
    response_content = request.execute()
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/oauth2client/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/apiclient/googleapiclient/http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/oauth2client/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/oauth2client/oauth2client/client.py", line 563, in new_request
    redirections, connection_type)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/httplib2/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/httplib2/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/httplib2/httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 522, in getresponse
    **extra_kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-a1e9f79a.400464599459611979/httplib2/httplib2/__init__.py", line 1106, in fixed_fetch
    validate_certificate=validate_certificate)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 293, in fetch
    return rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 413, in _get_fetch_result
    rpc.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
DeadlineExceededError: The API call urlfetch.Fetch() took too long to respond and was cancelled.
```

**Comment by simonhatch** [comment]
I think those are all the same call to /update_bugs_with_results, the overall call fails at the 10 min mark and we don't tick the metric if any exceptions are encountered. Will look at why those exceptions are occurring.

**Comment by simonhatch** [comment]
All the old bisects have been cancelled and their TryJob's have been deleted and the metric is ticking again, so closing this out.
