### ISSUE TITLE
Commit queue failing on catapult roll

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3491]
@nedn 

https://chromium-review.googlesource.com/c/475009/

Log only includes https://codereview.chromium.org/2768873004 "Make sure that trace are captured in results even when story run fails"

Failure:
https://build.chromium.org/p/tryserver.chromium.android/builders/android_n5x_swarming_rel/builds/155787
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Ftryserver.chromium.android%2Fandroid_n5x_swarming_rel%2F155787%2F%2B%2Frecipes%2Fsteps%2Ftelemetry_perf_unittests__with_patch__on_Android%2F0%2Fstdout
```
  Traceback (most recent call last):
    File "/b/swarm_slave/w/ir/tools/perf/measurements/smoothness_unittest.py", line 149, in testSmoothnessSurfaceFlingerMetricsCalculated
      results = self.RunMeasurement(measurement, ps, options=self._options)
    File "/b/swarm_slave/w/ir/third_party/catapult/telemetry/telemetry/testing/page_test_test_case.py", line 70, in RunMeasurement
      story_runner.Run(measurement, ps, options, results)
    File "/b/swarm_slave/w/ir/third_party/catapult/telemetry/telemetry/internal/story_runner.py", line 244, in Run
      _RunStoryAndProcessErrorIfNeeded(story, results, state, test)
    File "/b/swarm_slave/w/ir/third_party/catapult/telemetry/telemetry/internal/story_runner.py", line 114, in _RunStoryAndProcessErrorIfNeeded
      test.DidRunPage(state.platform)
    File "/b/swarm_slave/w/ir/third_party/catapult/common/py_trace_event/py_trace_event/trace_event_impl/decorators.py", line 52, in traced_function
      return func(*args, **kwargs)
    File "/b/swarm_slave/w/ir/tools/perf/measurements/smoothness.py", line 65, in DidRunPage
      self._tbm.DidRunStory(platform)
  TypeError: DidRunStory() takes exactly 3 arguments (2 given)
```

**Comment by nedn** [comment]
Manual roll: https://chromium-review.googlesource.com/c/475132/
