### ISSUE TITLE
Telemetry fails to import numpy on Python 2.7.10 (and over)

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3580]
Following the advice from [record_wpr](https://cs.chromium.org/chromium/src/tools/perf/record_wpr?rcl=17d5597c638435b1b8fe60fe6e34da8dd7da3daa&l=25) I tried to install python 2.7.10 (and also 2.7.13) using:

```
$ curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
$ pyenv install 2.7.10
# Update PATH as requited
$ pyenv global 2.7.10
$ python --version
2.7.10
```

But now all Telemetry commands (both `run_benchmark` and `wpr_record`) fail with:

```
Traceback (most recent call last):
  <module> at /usr/local/google/code/clankium/src/tools/perf/run_benchmark:9
    from core import trybot_command
[...]
    from telemetry.util import color_histogram
  <module> at /usr/local/google/code/clankium/src/third_party/catapult/telemetry/telemetry/util/color_histogram.py:13
    np = external_modules.ImportOptionalModule('numpy')
  ImportOptionalModule at /usr/local/google/code/clankium/src/third_party/catapult/telemetry/telemetry/internal/util/external_modules.py:51
    return ImportRequiredModule(module)
  ImportRequiredModule at /usr/local/google/code/clankium/src/third_party/catapult/telemetry/telemetry/internal/util/external_modules.py:34
    module = importlib.import_module(module)
  import_module at /usr/local/google/home/perezju/.pyenv/versions/2.7.13/lib/python2.7/importlib/__init__.py:37
    __import__(name)
  <module> at /usr/local/google/code/clankium/src/third_party/catapult/telemetry/third_party/numpy/lib/numpy_linux_x86_64_58b6664311a625727f246e3783571dad940bd934/numpy/__init__.py:142
    from . import add_newdocs
ImportError: cannot import name add_newdocs
```

Has anybody seen this issue?

**Comment by kenrussell** [comment]
Searching for that undefined symbol turns up some hits. We haven't seen this on any of the workstations here, so could you please help us figure out why this is happening on your machine so we can try to add mitigations? See this for example:

https://github.com/scikit-learn/scikit-learn/issues/7542
https://www.google.com/search?q=PyFPE_jbuf

**Comment by kainino0x** [comment]
Just a clarifying note, the symbol above (PyFPE_jbuf) was seen in #2865:

```
$ tools/perf/run_benchmark --browser list
WARNING:root:Unable to import numpy: /usr/local/google/code/clankium/src/third_party/catapult/telemetry/third_party/numpy/lib/numpy_linux_x86_64_58b6664311a625727f246e3783571dad940bd934/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf
WARNING:root:Unable to import numpy: cannot import name add_newdocs
WARNING:root:Unable to import psutil: No module named psutil
```

It seems to be the root issue.

@perezju, thanks for the report. It's important that we figure out how to make this dependency more robust.

As @kenrussell pointed out, this issue has been seen online and is always solved by removing the system version of numpy. It seems there must be a conflict, but I don't know why it's taking priority for the `dlopen` calls in numpy - my system copy of numpy (different version) does not cause issues. Can you please send the output of these commands (my output for reference):

```
$ python -c 'import numpy; print numpy.__path__, numpy.__version__'
['/usr/lib/python2.7/dist-packages/numpy'] 1.8.2

$ echo $LD_LIBRARY_PATH
:/usr/local/google/home/kainino/homebrew/lib:/usr/local/google/home/kainino/homebrew/lib

$ echo $PYTHONPATH
/usr/local/buildtools/current/sitecustomize
```

**Comment by perezju** [comment]
The new managed environment I'm trying to set up is the one triggering the error.

```
# Switching to the managed environment
$ pyenv global 2.7.10

$ tools/perf/run_benchmark --browser list
WARNING:root:Unable to import numpy: /usr/local/google/code/clankium/src/third_party/catapult/telemetry/third_party/numpy/lib/numpy_linux_x86_64_58b6664311a625727f246e3783571dad940bd934/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf
WARNING:root:Unable to import numpy: cannot import name add_newdocs
WARNING:root:Unable to import numpy: No module named psutil

# numpy is not installed, so we don't expect to see it there
$ python -c 'import numpy; print numpy.__path__, numpy.__version__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
ImportError: No module named numpy

$ echo $LD_LIBRARY_PATH

$ echo $PYTHONPATH
/usr/local/buildtools/current/sitecustomize

$ python -c 'import sys; print sys.executable, sys.version'
/usr/local/google/home/perezju/.pyenv/versions/2.7.10/bin/python 2.7.10 (default, May 22 2017, 17:05:46) 
[GCC 4.8.4]
```

Going back to my system python (whatever came pre-installed on the workstation), things seem to work fine.

```
# Switching back to my system python
$ pyenv global system

$ tools/perf/run_benchmark --browser list
WARNING:root:Imported numpy from /usr/local/google/code/clankium/src/third_party/catapult/telemetry/third_party/numpy/lib/numpy_linux_x86_64_58b6664311a625727f246e3783571dad940bd934/numpy/__init__.pyc
WARNING:root:Imported numpy from /usr/local/google/code/clankium/src/third_party/catapult/telemetry/third_party/numpy/lib/numpy_linux_x86_64_58b6664311a625727f246e3783571dad940bd934/numpy/__init__.pyc
WARNING:root:Imported psutil from /usr/lib/python2.7/dist-packages/psutil/__init__.pyc

# I do have a numpy installed, but it's not the one that telemetry picks up
$ python -c 'import numpy; print numpy.__path__, numpy.__version__'
['/usr/lib/python2.7/dist-packages/numpy'] 1.8.2

$ echo $LD_LIBRARY_PATH

$ echo $PYTHONPATH
/usr/local/buildtools/current/sitecustomize

/usr/bin/python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
```

For reference this is [the patch](https://codereview.chromium.org/2897253002) I'm using to make the import errors on Telemetry non-fatal.

**Comment by nedn** [comment]
Any update on this?

**Comment by kainino0x** [comment]
Apologies, I keep forgetting to go back to this.

I haven't had time to reproduce this. I don't know anything about pyenv so I have no idea how it's setting things up, but apparently it's causing some weirdness with the native code imports.

**Comment by nedn** [comment]
I talked to Kai offline and it seems like producibility is the main problem. 
However, it worths noting that we are migrating wpr to Go, which mean we can ignore the problem of python version for WPR recording tool. 

@perezju seems like you have a workaround for now, does this sound ok?

**Comment by perezju** [comment]
I don't have a workaround, but I haven't had a need to record WPR archives again recently. I think it's probably fine to wait until the migration to Go.
