### ISSUE TITLE
A Bug?

### ISSUE THREAD

**Issue by barnett-yuxiang** [catapult-project/catapult#3603]
Hi All:
    I git clone the repository, and run "。／run_systrace.py -t 5" get error message as follow

```python
yuxiang$ ~/repo_github/catapult/systrace/systrace/run_systrace.py -t 5 gfx view input wm am -o trace.html
Starting tracing (5 seconds)
Tracing completed. Collecting output...
Outputting Systrace results...
Tracing complete, writing results

Traceback (most recent call last):
  File "/Users/yulong/repo_github/catapult/systrace/systrace/run_systrace.py", line 199, in <module>
    main()
  File "/Users/yulong/repo_github/catapult/systrace/systrace/run_systrace.py", line 196, in main
    main_impl(sys.argv)
  File "/Users/yulong/repo_github/catapult/systrace/systrace/run_systrace.py", line 193, in main_impl
    controller.OutputSystraceResults(write_json=options.write_json)
  File "/Users/yulong/repo_github/catapult/systrace/systrace/systrace_runner.py", line 68, in OutputSystraceResults
    self._out_filename)
  File "/Users/yulong/repo_github/catapult/systrace/systrace/output_generator.py", line 76, in GenerateHTMLOutput
    trace_viewer_html = _ReadAsset(systrace_dir, 'systrace_trace_viewer.html')
  File "/Users/yulong/repo_github/catapult/systrace/systrace/output_generator.py", line 53, in _ReadAsset
    return open(os.path.join(src_dir, filename)).read()
IOError: [Errno 2] No such file or directory: '/Users/yulong/repo_github/catapult/systrace/systrace/systrace_trace_viewer.html'
```

    I read the source code, debug and I find get_catapult_rev_in_git_ throw exception

```python
def get_catapult_rev_in_git_():
  try:
    catapult_rev = subprocess.check_output(
        ['git', 'rev-parse', 'HEAD'],
        shell=True, # Needed by Windows
        cwd=os.path.dirname(os.path.abspath(__file__))).strip()
  except (subprocess.CalledProcessError, OSError):
    catapult_rev = ''
  if not catapult_rev:
    return ''
  else:
    return catapult_rev
```

**Comment by wangzhen127** [comment]
Are you able to run " git rev-parse HEAD" on your machine? It needs to generate systrace_trace_viewer.html from trace viewer code in order to visualize the trace. We use the version to detect if that html file is already generated with the HEAD version.

**Comment by nickdesaulniers** [comment]
```sh
➜  catapult git:(master) git rev-parse HEAD
06fd359d488b119665f6281e31b98514b0cf77a3
```

I see the same error as OP.

**Comment by wangzhen127** [comment]
If you can run "git rev-parse HEAD" from command line, why would you get the error:
CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 1

Any problem of running command from python?
