### ISSUE TITLE
Perf dashboard report shows no graphs

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3619]
Trying to follow a link from [alerts page](https://chromeperf.appspot.com/group_report?rev=475528) to view an [individual graph](https://chromeperf.appspot.com/report?masters=ChromiumPerf&bots=android-nexus6&tests=system_health.memory_mobile%2Fmemory%3Achrome%3Aall_processes%3Areported_by_chrome%3Acc%3Aeffective_size_avg%2Fbackground_search%2Fbackground_search_google&checked=background_search_google%2Cbackground_search_google_ref%2Cref&rev=475683) leads to a page with no graphs.

On dev tools it shows a 500 when trying to post to [list_tests](https://chromeperf.appspot.com/list_tests).

@anniesullie

**Comment by anniesullie** [comment]
@simonhatch @eakuefner 

I'm seeing a lot of this in the logs:
```
'str' object does not support item assignment (/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/report.py", line 40, in post
    'test_suites': update_test_suites.FetchCachedTestSuites(),
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/update_test_suites.py", line 25, in FetchCachedTestSuites
    cached = stored_object.Get(cache_key)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 1087, in synctasklet_wrapper
    return taskletfunc(*args, **kwds).get_result()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/common/stored_object.py", line 53, in Get
    result = yield GetAsync(key)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/common/stored_object.py", line 63, in GetAsync
    yield set_future, get_future
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 624, in _finish
    result = [r.get_result() for r in self._results]
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/common/stored_object.py", line 237, in _GetValueFromDatastore
    yield entity.GetPartsAsync()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 430, in _help_tasklet_along
    value = gen.send(val)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/common/stored_object.py", line 120, in GetPartsAsync
    self.SetData(pickle.loads(serialized))
TypeError: 'str' object does not support item assignment
```

But when I go to the admin console and type in:
```
from dashboard import update_test_suites
print update_test_suites.FetchCachedTestSuites()
```

Everything goes fine. Any ideas?

**Comment by simonhatch** [comment]
I'll check this out.

**Comment by anniesullie** [comment]
I deleted a comment I wrote above because it looked at the wrong path. This is the actual log I'm getting, for /list_tests:

```
'NoneType' object has no attribute 'has_rows' (/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/list_tests.py", line 71, in post
    json.loads(test_path_dict), return_selected)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/list_tests.py", line 389, in GetTestsForTestPathDict
    return _GetSelectedTestPathsForDict(test_path_dict)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/list_tests.py", line 418, in _GetSelectedTestPathsForDict
    if test_key.has_rows:
AttributeError: 'NoneType' object has no attribute 'has_rows'
```

**Comment by simonhatch** [comment]
@benshayden @eakuefner 

Likely candidate is https://codereview.chromium.org/2895483002

Investigating a fix.

**Comment by simonhatch** [comment]
I can revert that in the meantime and deploy a new dashboard, and we can reland that with fixes.

**Comment by simonhatch** [comment]
There's also a 2nd exception in internal_model:

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/list_tests.py", line 71, in post
    json.loads(test_path_dict), return_selected)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/list_tests.py", line 389, in GetTestsForTestPathDict
    return _GetSelectedTestPathsForDict(test_path_dict)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/list_tests.py", line 415, in _GetSelectedTestPathsForDict
    ndb.Future.wait_all(test_key_futures)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 407, in wait_all
    ev.run1()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 268, in run1
    delay = self.run0()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 230, in run0
    callback(*args, **kwds)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 533, in _on_future_completion
    self._help_tasklet_along(ns, ds_conn, gen, val)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 444, in _help_tasklet_along
    self.set_result(result)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 327, in set_result
    callback(*args, **kwds)
  File "/base/data/home/apps/s~chromeperf/clean-benjhayden-e59e87ea.401674176589512295/dashboard/models/internal_only_model.py", line 26, in _post_get_hook
    assert False
AssertionError

**Comment by simonhatch** [comment]
New dashboard is up.

**Comment by benshayden** [comment]
Thanks, Simon!

In testing and running the deploy checklist, I only saw the AssertionError in _post_get_hook when trying to access internal-only data while not signed in, in which case /graph_json would have returned 500 anyway. Are you seeing that AssertionError while signed in or for non-internal-only data?

For the `AttributeError: 'NoneType' object has no attribute 'has_rows'`, I can't find any documentation to suggest that get_result() could return None. Would that happen when requesting a TestKey that doesn't exist?

@eakuefner

**Comment by simonhatch** [comment]
I started poking at this, from what I can see it tries to get ref by several names, only one of which would exist.

Yeah guessing normally it'd return the path name, and rely on /graph_json to 500 later.

**Comment by simonhatch** [comment]
So just checking that test_key exists, and added test coverage seems fine for first case just fine, the internal_only thing needs has_rows. Normally list_test queries use .query(has_rows=true/false) and thus don't need to actually get() the TestMetadata and that skirts the internal_only issue. Should we catch the assert and then avoid passing the path back? Tangent: Should internal_only_model perhaps raise some sort of InternalAccessException or something instead of a generic assert?

**Comment by simonhatch** [comment]
Will close this out since the graphs are showing again.
