### ISSUE TITLE
merge_traces is broken when using HTML files as input

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3642]
I have a fix, it's a one liner. Just filing the bug to track the issue

$ ~/code/chrome/src/third_party/catapult/tracing/bin/merge_traces ~/Downloads/bef.html ~/Downloads/aft.html -o diff.html
ERROR:root:Something went wrong:
Traceback (most recent call last):
  File "/Users/primiano/code/chrome/src/third_party/catapult/tracing/tracing_build/merge_traces.py", line 665, in Main
    MergeTraceFiles(args.input_traces, args.output_trace)
  File "/Users/primiano/code/chrome/src/third_party/catapult/tracing/tracing_build/merge_traces.py", line 362, in MergeTraceFiles
    input_traces[input_trace_filename] = LoadTrace(input_trace_filename)
  File "/Users/primiano/code/chrome/src/third_party/catapult/tracing/tracing_build/merge_traces.py", line 299, in LoadTrace
    return LoadHTMLTrace(filename)
  File "/Users/primiano/code/chrome/src/third_party/catapult/tracing/tracing_build/merge_traces.py", line 312, in LoadHTMLTrace
    for sub_trace in html2trace.ReadTracesFromHTMLFilePath(filename):
  File "/Users/primiano/code/chrome/src/third_party/catapult/tracing/tracing_build/html2trace.py", line 59, in ReadTracesFromHTMLFilePath
    return map(json.load, _ExtractTraceDataFromHTMLFile((html_file_handle)))
  File "/Users/primiano/code/chrome/src/third_party/catapult/tracing/tracing_build/html2trace.py", line 63, in _ExtractTraceDataFromHTMLFile
    assert IsHTMLTrace(html_file_handle)
  File "/Users/primiano/code/chrome/src/third_party/catapult/tracing/tracing_build/html2trace.py", line 23, in IsHTMLTrace
    trace_file_handle.seek(0)
AttributeError: 'str' object has no attribute 'seek'

**Comment by primiano** [comment]
https://codereview.chromium.org/2930013002
