### ISSUE TITLE
update_systrace_trace_viewer.py fails silently

### ISSUE THREAD

**Issue by Knio** [catapult-project/catapult#3682]
Version: bdff8501d71be9e9e710f3effa09a5c3a7acaa6a

Expected result: Should update whatever files it's supposed to update.
Expected result 2: Should print an error message and return a nonzero return code if it had a problem updating.

Actual output: No output, return code 0, and failed to update

Additionally, there are no obvious instructions telling you that you need to run this update tool before systrace will be usable. The README does state "Systrace will auto update systrace_trace_viewer.html if update_systrace_trace_viewer.py exists.", but this appears to be false.

Example 1:
```sh
$ ./update_systrace_trace_viewer.py 
$ echo $?
0

```

Example 2:
```sh
$ sudo ./systrace/systrace/run_systrace.py --target=linux -t 5
starting tracing.
Starting tracing (5 seconds)
Tracing completed. Collecting output...
Outputting Systrace results...
Tracing complete, writing results
Traceback (most recent call last):
  File "./systrace/systrace/run_systrace.py", line 199, in <module>
    main()
  File "./systrace/systrace/run_systrace.py", line 196, in main
    main_impl(sys.argv)
  File "./systrace/systrace/run_systrace.py", line 193, in main_impl
    controller.OutputSystraceResults(write_json=options.write_json)
  File "/home/tom/src/catapult/systrace/systrace/systrace_runner.py", line 68, in OutputSystraceResults
    self._out_filename)
  File "/home/tom/src/catapult/systrace/systrace/output_generator.py", line 76, in GenerateHTMLOutput
    trace_viewer_html = _ReadAsset(systrace_dir, 'systrace_trace_viewer.html')
  File "/home/tom/src/catapult/systrace/systrace/output_generator.py", line 53, in _ReadAsset
    return open(os.path.join(src_dir, filename)).read()
IOError: [Errno 2] No such file or directory: '/home/tom/src/catapult/systrace/systrace/systrace_trace_viewer.html'
$ ./systrace/systrace/update_systrace_trace_viewer.py 
$ sudo ./systrace/systrace/run_systrace.py --target=linux -t 5
starting tracing.
Starting tracing (5 seconds)
Tracing completed. Collecting output...
Outputting Systrace results...
Tracing complete, writing results
Traceback (most recent call last):
  File "./systrace/systrace/run_systrace.py", line 199, in <module>
    main()
  File "./systrace/systrace/run_systrace.py", line 196, in main
    main_impl(sys.argv)
  File "./systrace/systrace/run_systrace.py", line 193, in main_impl
    controller.OutputSystraceResults(write_json=options.write_json)
  File "/home/tom/src/catapult/systrace/systrace/systrace_runner.py", line 68, in OutputSystraceResults
    self._out_filename)
  File "/home/tom/src/catapult/systrace/systrace/output_generator.py", line 76, in GenerateHTMLOutput
    trace_viewer_html = _ReadAsset(systrace_dir, 'systrace_trace_viewer.html')
  File "/home/tom/src/catapult/systrace/systrace/output_generator.py", line 53, in _ReadAsset
    return open(os.path.join(src_dir, filename)).read()
IOError: [Errno 2] No such file or directory: '/home/tom/src/catapult/systrace/systrace/systrace_trace_viewer.html'
```

**Comment by Knio** [comment]
This looks to be related to #3603.

The problem is here: https://github.com/catapult-project/catapult/blob/master/systrace/systrace/update_systrace_trace_viewer.py#L49

with `shell=True`, the arguments to subprocess should be a single string, not a list of args. See https://docs.python.org/2/library/subprocess.html#frequently-used-arguments

Also, there's no reason why `shell=True` should be used here. Windows has no problem executing sub processes.
