### ISSUE TITLE
run_benchmark fails with MapFunctionError "sample_metric.html" is not a registered metric.

### ISSUE THREAD

**Issue by xunjieli** [catapult-project/catapult#3686]
Steps to repro
- telemetry/examples/record_wpr  simple_story_set --browser=system --pageset-repeat=1
- telemetry/examples/run_benchmark tbm_sample.tbm_sample --browser=system --pageset-repeat=1

The second step fails with 

**MapFunctionError: "sample_metric.html" is not a registered metric.**
    at runMetrics (/usr/local/google/home/xunjieli/catapult/tracing/tracing/metrics/metric_map_function.html:38:15)
    at metricMapFunction (/usr/local/google/home/xunjieli/catapult/tracing/tracing/metrics/metric_map_function.html:73:24)
    at Object.mapSingleTrace (/tracing/mre/map_single_trace.html:40:7)
    at eval (/usr/local/google/home/xunjieli/catapult/tracing/tracing/mre/map_single_trace_cmdline.html:61:18)
    at Object.runAndConvertErrorsToFailures (/tracing/mre/map_single_trace.html:25:10)
    at mapSingleTraceWithResult (/usr/local/google/home/xunjieli/catapult/tracing/tracing/mre/map_single_trace_cmdline.html:52:12)
    at Object.mapSingleTraceMain (/usr/local/google/home/xunjieli/catapult/tracing/tracing/mre/map_single_trace_cmdline.html:77:20)
    at eval (/usr/local/google/home/xunjieli/catapult/tracing/tracing/mre/map_single_trace_cmdline.html:90:15)
    at Object.loadHTMLFile (/usr/local/google/home/xunjieli/catapult/third_party/vinn/vinn/html_imports_loader.js:140:5)
    at /usr/local/google/home/xunjieli/catapult/third_party/vinn/vinn/d8_bootstrap.js:151:19

/cc @nedn

**Comment by nedn** [comment]
I am seeing the sample metric in https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/all_metrics.html#L11. 

Any idea?
@benshayden @eakuefner

**Comment by eakuefner** [comment]
The bug here is that metrics register and are to be specified by name, rather than filename. See https://github.com/catapult-project/catapult/blob/master/tracing/tracing/metrics/sample_metric.html#L39.

The fix here is to change this line https://github.com/catapult-project/catapult/blob/ff40d4569c8bcf2eed27ed49682e7b8198d24dc1/telemetry/examples/benchmarks/tbm_benchmark.py#L16 to refer to `sampleMetric` rather than `sample_metric.html`.

**Comment by xunjieli** [comment]
Thanks. That works. I will do it in other CL that I am working on.

**Comment by nedn** [comment]
I sent out a fix.
