### ISSUE TITLE
Exception in update_bug_with_results

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3778]
We got an alert that not all bugs are being updated correctly.

Looking at go/chromeperf-logs, url being requested appears to be: https://cr-buildbucket.appspot.com/api/buildbucket/v1/builds/8971262121741666416?alt=json which corresponds to http://crbug.com/755224 and https://chromeperf.appspot.com/buildbucket_job_status/8971262121741666416 and https://build.chromium.org/p/tryserver.chromium.perf/builders/mac_pro_perf_bisect/builds/475. Here are the error logs:

```
Caught Exception UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 114: ordinal not in range(128) (/base/data/home/apps/s~chromeperf/clean-sullivan-03fe101a.403289651732382914/dashboard/update_bug_with_results.py:110)
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-03fe101a.403289651732382914/dashboard/update_bug_with_results.py", line 107, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-03fe101a.403289651732382914/dashboard/update_bug_with_results.py", line 153, in _CheckJob
    _CheckBisectJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-03fe101a.403289651732382914/dashboard/update_bug_with_results.py", line 168, in _CheckBisectJob
    _PostSuccessfulResult(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-03fe101a.403289651732382914/dashboard/update_bug_with_results.py", line 266, in _PostSuccessfulResult
    owner, comment = _GetCulpritCLOwnerAndComment(job, authors_to_cc)
  File "/base/data/home/apps/s~chromeperf/clean-sullivan-03fe101a.403289651732382914/dashboard/update_bug_with_results.py", line 231, in _GetCulpritCLOwnerAndComment
    comment)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 114: ordinal not in range(128)
```

Looking at the bisect results: https://luci-logdog.appspot.com/v/?s=chrome%2Fbb%2Ftryserver.chromium.perf%2Fmac_pro_perf_bisect%2F475%2F%2B%2Frecipes%2Fsteps%2FReading_culprit_cl_information.__2_%2F0%2Flogs%2Fjson.output%2F0

The problem seems to be the unicode character in the author name:
```"author": "Sidney San Mart\u00edn",```

Anyone have time to take a look? @simonhatch @eakuefner @benshayden

**Comment by anniesullie** [comment]
Actually have some spare time today, going to take a look.
