### ISSUE TITLE
DeadlineExceededError during taskqueue.Add()

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3931]
https://pinpoint-dot-chromeperf.appspot.com/job/15b64f34780000

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-ee710c11.404413477922757601/dashboard/pinpoint/models/job.py", line 140, in Run
    self.Schedule()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-ee710c11.404413477922757601/dashboard/pinpoint/models/job.py", line 126, in Schedule
    countdown=_TASK_INTERVAL)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2515, in add
    queue_name=queue_name, transactional=transactional)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 1213, in add
    return self.add_async(queue_name, transactional).get_result()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/taskqueue/taskqueue.py", line 2138, in ResultHook
    rpc.check_success()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
DeadlineExceededError: The API call taskqueue.BulkAdd() took too long to respond and was cancelled.
```

**Comment by dave-2** [comment]
Didn't even know this was possible.

Google suggests adding a retry to the taskqueue API call.
https://issuetracker.google.com/issues/35897969#comment20

**Comment by anniesullie** [comment]
Perf dashboard batches the task queue tasks into groups I think. (check add_point.py)

**Comment by dave-2** [comment]
The error message is misleading. We don't do any batching of tasks, because each Job has only one task and schedules its task independently from other Jobs.

I also checked `add_point.py` and it has a group of tasks, but it [adds them synchronously](https://chromium.googlesource.com/catapult/+/HEAD/dashboard/dashboard/add_point.py#265) (it actually looks like a bug in the code).

**Comment by simonhatch** [comment]
Nice find, that's a little strange. Under the hood .add() should be identical (https://cloud.google.com/appengine/docs/standard/python/refdocs/modules/google/appengine/api/taskqueue/taskqueue)

Can probably just change the block to async them all and wait on the results.

**Comment by dave-2** [comment]
I misread the code. It chunks the tasks into groups of `MAX_TASKS_PER_ADD` (100) and adds each group synchronously. That's probably not so bad.
