### ISSUE TITLE
[📍] Pinpoint job failure while reading DEPS

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3957]
```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-778430a2.404605615254613710/dashboard/pinpoint/models/job.py", line 192, in Run
    self.state.Explore()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-778430a2.404605615254613710/dashboard/pinpoint/models/job.py", line 299, in Explore
    midpoint = change_module.Change.Midpoint(change_a, change_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-778430a2.404605615254613710/dashboard/pinpoint/models/change/change.py", line 117, in Midpoint
    commits_midpoint = _FindMidpoints(commits_a, commits_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-778430a2.404605615254613710/dashboard/pinpoint/models/change/change.py", line 200, in _FindMidpoints
    deps_a = commit_a.Deps()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-778430a2.404605615254613710/dashboard/pinpoint/models/change/commit.py", line 52, in Deps
    dep_string_parts = dep_string.split('@')
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by dave-2** [comment]
It looks like the `DEPS` file format changed. There's a new conditional DEPS feature, and `src/DEPS` was updated in [chromium/src@7af36895](https://chromium.googlesource.com/chromium/src/+/7af36895aed21beb249c10ea8dfd8f2c62e02539). In the new format, a DEP can be a string of `repo@git_hash`, or a dict of `{'url': 'repo@git_hash', 'condition': 'condition_string'}

We'll need to update the DEPS parsing to handle the new format.
