### ISSUE TITLE
Lot of "Bisect failed for unknown reasons" on android bots

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3971]
Quite a lot of bisects came back today in my inbox with this error.
For instance:
https://bugs.chromium.org/p/chromium/issues/detail?id=774094

It seems mostly related with android bots

**Comment by primiano** [comment]
@simonhatch @anniesullie

**Comment by simonhatch** [comment]
Hmm not familliar, kinda looks like it's having trouble applying a patch:

Traceback (most recent call last):
  File "/b/build_internal/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/run.py", line 376, in _old_run
    recipe_result = recipe_script.run(api, properties)
  File "/b/build_internal/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/loader.py", line 98, in run
    self.run_steps, properties, self.PROPERTIES, api=api)
  File "/b/build_internal/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/loader.py", line 627, in invoke_with_properties
    **additional_args)
  File "/b/build_internal/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/loader.py", line 588, in _invoke_with_properties
    return callable_obj(*props, **additional_args)
  File "/b/build_internal/scripts/slave/recipes/clank/bisect.py", line 150, in RunSteps
    cwd=api.path['start_dir'].join('src', 'clank'))
  File "/b/build_internal/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/recipe_api.py", line 745, in _inner
    return func(*a, **kw)
  File "/b/build_internal/scripts/slave/recipe_modules/tryserver_apply_issue/api.py", line 34, in maybe_apply_issue
    patch_repo_url = self.m.properties['patch_repository_url']
  File "/b/build_internal/scripts/slave/.recipe_deps/recipe_engine/recipe_modules/properties/api.py", line 46, in __getitem__
    return self._properties[key]
  File "/b/build_internal/scripts/slave/.recipe_deps/recipe_engine/recipe_engine/types.py", line 66, in __getitem__
    return self._d[key]
KeyError: 'patch_repository_url'

**Comment by simonhatch** [comment]
Fix in crbug.com/774171
