### ISSUE TITLE
Perf dasbhoard: 500 errors viewing /group_report

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3985]
The XHR to /group_report is failing with 500 errors. Looks like an error in `StoredObject`. From the logs:

```
invalid load key, '_'. (/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-6f19655f.404775404309272094/dashboard/group_report.py", line 76, in post
    'test_suites': update_test_suites.FetchCachedTestSuites(),
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-6f19655f.404775404309272094/dashboard/update_test_suites.py", line 25, in FetchCachedTestSuites
    cached = stored_object.Get(cache_key)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 1087, in synctasklet_wrapper
    return taskletfunc(*args, **kwds).get_result()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-6f19655f.404775404309272094/dashboard/common/stored_object.py", line 39, in Get
    result = yield GetAsync(key)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-6f19655f.404775404309272094/dashboard/common/stored_object.py", line 48, in GetAsync
    yield entity.GetPartsAsync()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 430, in _help_tasklet_along
    value = gen.send(val)
  File "/base/data/home/apps/s~chromeperf/clean-simonhatch-6f19655f.404775404309272094/dashboard/common/stored_object.py", line 102, in GetPartsAsync
    self.SetData(pickle.loads(serialized))
UnpicklingError: invalid load key, '_'.
```

**Comment by simonhatch** [comment]
This seems to have passed, might have been some problem updating the cached test suite object. The errors stopped shortly after the last call to /update_test_suites. Another reason to remove this entirely: #3234

**Comment by simonhatch** [comment]
Going to close this out, haven't seen these kind of issues in a while and unlikely to see them again since we've stripped /update_test_suites down quite a bit.
