### ISSUE TITLE
UnicodeEncodeError in trace processing

### ISSUE THREAD

**Issue by maxlgu** [catapult-project/catapult#3999]
I found such a tracing error while running cluster telemetry, happening for www.bell.ca for all three retries.

website: www.bell.ca
config: --pageset-repeat=1 --output-format=csv --traffic-setting=Regular-3G --use-live-sites
bot: Android N5
pageset: mobile10k
Patches:
https://chromium-review.googlesource.com/c/chromium/src/+/727365
https://chromium-review.googlesource.com/c/catapult/+/727363
swarming logs (more running details): 
https://chrome-swarming.appspot.com/task?id=396f7910f26a0d10&refresh=10&show_raw=1

----------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/b/storage/chromium/src/third_party/catapult/tracing/tracing/mre/threaded_work_queue.py", line 86, in _TryToRunOneTask
    task()
  File "/b/storage/chromium/src/third_party/catapult/tracing/tracing/mre/threaded_work_queue.py", line 71, in RunTask
    cb(*args, **kwargs)
  File "/b/storage/chromium/src/third_party/catapult/tracing/tracing/mre/map_runner.py", line 58, in _ProcessOneTrace
    run_reporter.DidAddFailure(f)
  File "/b/storage/chromium/src/third_party/catapult/tracing/tracing/mre/gtest_progress_reporter.py", line 24, in DidAddFailure
    print >> self._output_stream, failure.stack
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 35: ordinal not in range(128)

**Comment by benshayden** [comment]
Started https://chromium-review.googlesource.com/c/catapult/+/740908

**Comment by maxlgu** [comment]
Thanks!
