### ISSUE TITLE
[📍] Gitiles timeout failures

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4049]
About 1 in 10 jobs are failing with Gitiles timeout errors.
We can take a few approaches:
* Increase the timeout.
* Reduce the reliance on Gitiles by doing caching in the Datastore.
* Ask whoever owns Gitiles for help.

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/job.py", line 202, in Run
    self.state.Explore()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/job.py", line 309, in Explore
    midpoint = change_module.Change.Midpoint(change_a, change_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/change/change.py", line 117, in Midpoint
    commits_midpoint = _FindMidpoints(commits_a, commits_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/change/change.py", line 195, in _FindMidpoints
    commit_midpoint = commit_module.Commit.Midpoint(commit_a, commit_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/change/commit.py", line 145, in Midpoint
    commit_a.git_hash, commit_b.git_hash)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/services/gitiles_service.py", line 63, in CommitRange
    response = _RequestJson(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/services/gitiles_service.py", line 90, in _RequestJson
    return json.loads(_Request(url)[len(_PADDING):])
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/services/gitiles_service.py", line 98, in _Request
    return _RequestAndProcessHttpErrors(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/services/gitiles_service.py", line 103, in _RequestAndProcessHttpErrors
    response = urlfetch.fetch(url, deadline=30)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 293, in fetch
    return rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 463, in _get_fetch_result
    'Deadline exceeded while waiting for HTTP response from URL: ' + url)
DeadlineExceededError: Deadline exceeded while waiting for HTTP response from URL: https://chromium.googlesource.com/chromium/src/+log/bb2a003f3be6c19476e36fb1b12141b2d8139e21..81abc648e801e288b9c43a5c409d2d7285444f98?format=JSON
```

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/job.py", line 202, in Run
    self.state.Explore()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/job.py", line 309, in Explore
    midpoint = change_module.Change.Midpoint(change_a, change_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/change/change.py", line 117, in Midpoint
    commits_midpoint = _FindMidpoints(commits_a, commits_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/change/change.py", line 200, in _FindMidpoints
    deps_a = commit_a.Deps()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/pinpoint/models/change/commit.py", line 47, in Deps
    self.repository_url, self.git_hash, 'DEPS')
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/services/gitiles_service.py", line 85, in FileContents
    return base64.b64decode(_Request(url))
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/services/gitiles_service.py", line 96, in _Request
    return _RequestAndProcessHttpErrors(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-2671b653.405496494088448806/dashboard/services/gitiles_service.py", line 103, in _RequestAndProcessHttpErrors
    response = urlfetch.fetch(url, deadline=30)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 293, in fetch
    return rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 413, in _get_fetch_result
    rpc.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
DeadlineExceededError: The API call urlfetch.Fetch() took too long to respond and was cancelled.
```

**Comment by dave-2** [comment]
Timeout increased. For further caching work, see #4114.
