### ISSUE TITLE
add_reserved_diagnostics fails on v8.browsing_desktop output

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4099]
```
Traceback (most recent call last):
  File "../../../../tracing/bin/add_reserved_diagnostics", line 105, in <module>
    sys.exit(main())
  File "../../../../tracing/bin/add_reserved_diagnostics", line 57, in main
    'name', 'storyTags', 'stories'))
  File "/usr/local/google/home/simonhatch/chromium/catapult/tracing/tracing/value/merge_histograms.py", line 29, in MergeHistograms
    js_args=[os.path.abspath(json_path)] + list(groupby))
  File "/usr/local/google/home/simonhatch/chromium/catapult/third_party/vinn/vinn/_vinn.py", line 188, in RunFile
    return _RunFileWithD8(temp_boostrap_file, js_args, v8_args, stdout, stdin)
  File "/usr/local/google/home/simonhatch/chromium/catapult/third_party/vinn/vinn/_vinn.py", line 267, in _RunFileWithD8
    'Exception raised when executing %s:\n%s' % (js_file_path, out))
RuntimeError: Exception raised when executing /tmp/tmpyTQTtL/_tmp_boostrap.js:
/tracing/value/diagnostics/diagnostic_map.html:191: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
            this.get(tr.v.d.RESERVED_NAMES.MERGED_FROM)) {
                 ^
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Map.mergeRelationships (/tracing/value/diagnostics/diagnostic_map.html:191:18)
    at HistogramSet.mergeRelationships (/tracing/value/histogram_set.html:412:26)
    at eval (/usr/local/google/home/simonhatch/chromium/catapult/tracing/tracing/value/merge_histograms_cmdline.html:80:20)
    at Object.loadHTMLFile (/usr/local/google/home/simonhatch/chromium/catapult/third_party/vinn/vinn/html_imports_loader.js:140:5)
    at /usr/local/google/home/simonhatch/chromium/catapult/third_party/vinn/vinn/d8_bootstrap.js:151:19

```

@eakuefner

**Comment by eakuefner** [comment]
I'll take this -- looking into it.

**Comment by eakuefner** [comment]
This is **fixed**.
