### ISSUE TITLE
[📍] Cache Gitiles results

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4114]
We're seeing some jobs that don't stop running. The taskqueue fails to reschedule.
I looked through the logs, and most of them look like deadline exceeded errors.
I looked at the Stackdriver traces, and the long-running tasks almost always involve long calls to gitiles to fetch `DEPS` files.

So we want to implement datastore caching of Gitiles results, being careful not to cache results for `master` or `head`. This will also help with #4049 (gitiles timeouts) by reducing the number of calls to Gitiles and reducing the overall load on Gitiles.

**Comment by dave-2** [comment]
Seeing another related error.
429 is "too many requests"
```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/pinpoint/models/job.py", line 202, in Run
    self.state.Explore()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/pinpoint/models/job.py", line 315, in Explore
    midpoint = change_module.Change.Midpoint(change_a, change_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/pinpoint/models/change/change.py", line 117, in Midpoint
    commits_midpoint = _FindMidpoints(commits_a, commits_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/pinpoint/models/change/change.py", line 195, in _FindMidpoints
    commit_midpoint = commit_module.Commit.Midpoint(commit_a, commit_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/pinpoint/models/change/commit.py", line 172, in Midpoint
    commit_a.git_hash, commit_b.git_hash)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/services/gitiles_service.py", line 63, in CommitRange
    response = _RequestJson(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/services/gitiles_service.py", line 90, in _RequestJson
    return json.loads(_Request(url)[len(_PADDING):])
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/services/gitiles_service.py", line 98, in _Request
    return _RequestAndProcessHttpErrors(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a586b007.406356290390102364/dashboard/services/gitiles_service.py", line 110, in _RequestAndProcessHttpErrors
    (response.status_code, url))
Error: Server returned HTTP code 429 for https://chromium.googlesource.com/chromium/src/+log/ec25b51043b153b0b79fa7a0ff28b069e71e498f..b8f1d95f69851aad4474717d7e8dd065438ecd05?format=JSON
```
