### ISSUE TITLE
adb_profile_chrome_startup should make sure that /sdcard/Download exists before recording the trace

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#4125]
I ran into this problem today while trying to run adb_profile_chrome_startup to reproduce #4100. On a newly flashed Nexus 5X, when I ran:

```
https://github.com/catapult-project/catapult/issues/4100
```

I got:

```
Capturing 5-second Browser Startup Trace + atrace. Press Enter to stop early...Stopping...
Warning: Exception getting results from Browser Startup Trace:
<class 'devil.android.device_errors.AdbCommandFailedError'>
done
Traceback (most recent call last):
  File "./systrace/bin/adb_profile_chrome_startup", line 114, in <module>
    sys.exit(main())
  File "./systrace/bin/adb_profile_chrome_startup", line 105, in main
    write_json=options.write_json)
  File "/usr/local/google/home/charliea/github/catapult/systrace/profile_chrome/profiler.py", line 102, in CaptureProfile
    all_results = controller.StopTracing()
  File "/usr/local/google/home/charliea/github/catapult/systrace/systrace/tracing_controller.py", line 210, in StopTracing
    timeout=self._controller_config.collection_timeout)
  File "/usr/local/google/home/charliea/github/catapult/systrace/profile_chrome/../../common/py_utils/py_utils/__init__.py", line 101, in RunWithTimeout
    return timeout_retry.Run(func, timeout, 0, args=args)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/utils/timeout_retry.py", line 157, in Run
    error_log_func=error_log_func)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/utils/reraiser_thread.py", line 186, in JoinAll
    self._JoinAll(watcher, timeout)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/utils/reraiser_thread.py", line 158, in _JoinAll
    thread.ReraiseIfException()
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/utils/reraiser_thread.py", line 81, in run
    self._ret = self._func(*self._args, **self._kwargs)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/utils/timeout_retry.py", line 150, in <lambda>
    child_thread = reraiser_thread.ReraiserThread(lambda: func(*args, **kwargs),
  File "/usr/local/google/home/charliea/github/catapult/systrace/profile_chrome/chrome_startup_tracing_agent.py", line 96, in GetResults
    with open(self._PullTrace(), 'r') as f:
  File "/usr/local/google/home/charliea/github/catapult/systrace/profile_chrome/chrome_startup_tracing_agent.py", line 103, in _PullTrace
    self._device.PullFile(trace_file, host_file)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/decorators.py", line 51, in timeout_retry_wrapper
    return impl()
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/decorators.py", line 47, in impl
    return f(*args, **kwargs)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/device_utils.py", line 1726, in PullFile
    self.adb.Pull(device_path, host_path)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/sdk/adb_wrapper.py", line 474, in Pull
    self._RunDeviceAdbCmd(cmd, timeout, retries)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/sdk/adb_wrapper.py", line 301, in _RunDeviceAdbCmd
    check_error=check_error)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/decorators.py", line 51, in timeout_retry_wrapper
    return impl()
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/decorators.py", line 47, in impl
    return f(*args, **kwargs)
  File "/usr/local/google/home/charliea/github/catapult/devil/devil/android/sdk/adb_wrapper.py", line 281, in _RunAdbCmd
    args, output, status, device_serial)
devil.android.device_errors.AdbCommandFailedError: (device: 01fc26471832be6a) adb pull /sdcard/Download/chrome-profile-results-2017-12-15-204238 ./chrome-profile-results-2017-12-15-204238: failed with exit status 1 and output:
- remote object '/sdcard/Download/chrome-profile-results-2017-12-15-204238' does not exist
```

It wasn't until I did 

```
adb shell mkdir /sdcard/Download
```

that the command succeeded. Can we walter adb_profile_chrome_startup to ensure that this folder exists rather than just failing?

@jbudorick do you know how to triage this appropriately?

**Comment by normoes** [comment]
The file access happens in **systrace/profile_chrome/profiler.py** but is done using 
`with open(result, 'wb') as f:` which, as far as I know, also creates the file, if it should not be available.

Though, the error message tells something else, couldn't it be an issue of permissions?

**Comment by zeptonaut** [comment]
`with open(result, 'wb') as f:` will create the file if the directory exists, but the file doesn't, but the problem is that we don't check to make sure that the directory exists.

**Comment by normoes** [comment]
Yes, of course.
So, that seems to be the right place.
I'll give it a try, if that's OK with you.

**Comment by zeptonaut** [comment]
Thanks @normoes!

**Comment by msampathkumar** [comment]
Added pull request - https://github.com/catapult-project/catapult/pull/4600

With this change, the result will be generated in the specified location, even if the directory is not available. Please advice.

**Comment by normoes** [comment]
Yes.

Using `os.makedirs(...)` creates the directory structure, even if nested folders should be missing.

From [python docs](https://docs.python.org/3/library/os.html):

> os.makedirs(name, mode=0o777, exist_ok=False)
>     Recursive directory creation function. Like mkdir(), but makes all intermediate-level directories needed to contain the leaf directory.

**Comment by zeptonaut** [comment]
I think it won't let me assign the issue to people who aren't listed as contributors.

@msampathkumar if you have a pull request, could you please follow the instructions in [contributing.md](https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md)? Unfortunately, we don't use the normal pull request workflow for Chromium projects

**Comment by Softdude47** [comment]
<html>
I guess you should try this:

<b>import os</b>
path = '/path/to/directory/directory_name'
if <em>os.path.exists(path)</em> == None:
<em>os.mkdirs(path)
</em>
</html>
