### ISSUE TITLE
symbolize_trace_end_to_end_test_slow.SymbolizeTraceEndToEndTest flaky

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#4134]
See for example this test: https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/9714/steps/Native%20Heap%20Symbolizer%20Tests/logs/stdio

[1/5] symbolize_trace_end_to_end_test_slow.SymbolizeTraceEndToEndTest.testMacv1 passed
[2/5] symbolize_trace_end_to_end_test_slow.SymbolizeTraceEndToEndTest.testMacv1Breakpad failed unexpectedly:
  Downloading C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\data\mac_trace_v1_presymbolization.json.gz from gcs.
  Traceback (most recent call last):
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 133, in testMacv1Breakpad
      ['--use-breakpad-symbols'])
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 70, in _RunSymbolizationOnTrace
      _DownloadFromCloudStorage(trace_presymbolization_path)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 41, in _DownloadFromCloudStorage
      cloud_storage.GetIfChanged(path, cloud_storage.PARTNER_BUCKET)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 451, in GetIfChanged
      _GetLocked(bucket, expected_hash, file_path)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 349, in _GetLocked
      _RunCommand(['cp', url, partial_download_path.name])
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 154, in _RunCommand
      raise GetErrorObjectForCloudStorageStderr(stderr)
  CloudStorageError: Failure: (33, 'LockFileEx', 'The process cannot access the file because another process has locked a portion of the file.').
  
[3/5] symbolize_trace_end_to_end_test_slow.SymbolizeTraceEndToEndTest.testWin64v1 failed unexpectedly:
  Downloading C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\data\windows_trace_v1_presymbolization.json.gz from gcs.
  Traceback (most recent call last):
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 148, in testWin64v1
      [])
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 70, in _RunSymbolizationOnTrace
      _DownloadFromCloudStorage(trace_presymbolization_path)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 41, in _DownloadFromCloudStorage
      cloud_storage.GetIfChanged(path, cloud_storage.PARTNER_BUCKET)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 451, in GetIfChanged
      _GetLocked(bucket, expected_hash, file_path)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 349, in _GetLocked
      _RunCommand(['cp', url, partial_download_path.name])
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 154, in _RunCommand
      raise GetErrorObjectForCloudStorageStderr(stderr)
  CloudStorageError: Failure: (33, 'LockFileEx', 'The process cannot access the file because another process has locked a portion of the file.').
  
[4/5] symbolize_trace_end_to_end_test_slow.SymbolizeTraceEndToEndTest.testWin64v2 failed unexpectedly:
  Downloading C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\data\windows_trace_v2_presymbolization.json.gz from gcs.
  Traceback (most recent call last):
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 163, in testWin64v2
      [])
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 70, in _RunSymbolizationOnTrace
      _DownloadFromCloudStorage(trace_presymbolization_path)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\tracing\tracing\extras\symbolizer\symbolize_trace_end_to_end_test_slow.py", line 41, in _DownloadFromCloudStorage
      cloud_storage.GetIfChanged(path, cloud_storage.PARTNER_BUCKET)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 451, in GetIfChanged
      _GetLocked(bucket, expected_hash, file_path)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 349, in _GetLocked
      _RunCommand(['cp', url, partial_download_path.name])
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\common\py_utils\py_utils\cloud_storage.py", line 154, in _RunCommand
      raise GetErrorObjectForCloudStorageStderr(stderr)
  CloudStorageError: Failure: (33, 'LockFileEx', 'The process cannot access the file because another process has locked a portion of the file.').

**Comment by CalebRouleau** [comment]
Got a stack trace from inside gsutil:

        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\__main__.py", line 572, in _RunNamedCommandAndHandleExceptions
          user_project=user_project)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\command_runner.py", line 319, in RunNamedCommand
          return_code = command_inst.RunCommand()
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\commands\ls.py", line 566, in RunCommand
          exp_dirs, exp_objs, exp_bytes = ls_helper.ExpandUrlAndPrint(storage_url)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\ls_helper.py", line 192, in ExpandUrlAndPrint
          top_level_iterator.PeekException()
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\plurality_checkable_iterator.py", line 65, in _PopulateHead
          e = self.base_iterator.next()
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\wildcard_iterator.py", line 476, in IterAll
          expand_top_level_buckets=expand_top_level_buckets):
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\wildcard_iterator.py", line 215, in __iter__
          provider=self.wildcard_url.scheme, fields=listing_fields):
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\gcs_json_api.py", line 609, in ListObjects
          global_params=global_params)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\third_party\storage_apitools\storage_v1_client.py", line 1171, in List
          config, request, global_params=global_params)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\apitools\apitools\base\py\base_api.py", line 720, in _RunMethod
          http, http_request, **opts)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 351, in MakeRequest
          max_retry_wait, total_wait_sec))
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\gslib\util.py", line 1723, in WarnAfterManyRetriesHandler
          http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 341, in MakeRequest
          check_response_func=check_response_func)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\apitools\apitools\base\py\http_wrapper.py", line 391, in _MakeRequestNoRetry
          redirections=redirections, connection_type=connection_type)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\oauth2client\oauth2client\client.py", line 616, in new_request
          self._refresh(request_orig)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\oauth2client\oauth2client\client.py", line 875, in _refresh
          self.store.acquire_lock()
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\oauth2client\oauth2client\contrib\multistore_file.py", line 240, in acquire_lock
          self._multistore._lock()
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\oauth2client\oauth2client\contrib\multistore_file.py", line 300, in _lock
          self._file.open_and_lock()
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\oauth2client\oauth2client\contrib\locked_file.py", line 230, in open_and_lock
          self._opener.open_and_lock(timeout, delay)
        File "C:\Users\crouleau\src\src\third_party\catapult\third_party\gsutil\third_party\oauth2client\oauth2client\contrib\_win32_opener.py", line 75, in open_and_lock
          pywintypes.OVERLAPPED())
      error: (33, 'LockFileEx', 'The process cannot access the file because another process has locked a portion of the file.')

**Comment by CalebRouleau** [comment]
So we use the latest release of gsutil, version 4.28, but that uses an old version of oauth2client, 2.2.0 (4.1.2 is current). The change to update gsutil to 4.1.2 is out: https://github.com/GoogleCloudPlatform/gsutil/commit/114fc88c47657ab9b1669be7a82dfa847f2a856f
but it hasn't been released yet. 

The reason what's above matters is that gsutil 4.28 uses oauth2client.contrib.multistore_file, which is flaky (see trace above) and has been replaced with oauth2client.contrib.multiprocess_file_storage.

I think what is happening is that one of the two tests are calling gsutil methods at the same time, and the flaky lock acquisition in multistore_file is causing failures. (The reason for the lock is to rate-limit credentials requests.)

Two possible solutions:
1. Retry:
Two ways to add retries:
  a. The _lock() call in oauth2client's  is not doing retries because timeout is not being set. We could edit it to set it to some positive value. The problem with this method is that we would be editing third_party code, and I'm not sure what the process is for that.
  b. Instead we could add a retry to cloud_storage's _RunCommand when we fail with error code 33: "LockFileEx". If we do this we can add a note to remove the retry once gsutil/oauth2client is updated. 
2. Update the library:
I don't think this is a good solution until there's a new release out.

**Comment by CalebRouleau** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=796137&can=2&start=0&num=100&q=owner%3Ame&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&hotlist_id=

**Comment by CalebRouleau** [comment]
Closing this issue in favor of https://bugs.chromium.org/p/chromium/issues/detail?id=796137
