### ISSUE TITLE
[📍] Pinpoint still uses --isolated-script-test-chartjson-output

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4141]
The flag is being renamed to `--isolated-script-test-perf-output` (see [Chromium issue 744736](https://bugs.chromium.org/p/chromium/issues/detail?id=744736#c3))

It showed up as an error in this v8.runtime_stats.top_25 job:
https://pinpoint-dot-chromeperf.appspot.com/job/12ccbe03040000
```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-bd319d25.406548626035855371/dashboard/pinpoint/models/quest/execution.py", line 99, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-bd319d25.406548626035855371/dashboard/pinpoint/models/quest/read_value.py", line 165, in _Poll
    self._isolate_hash, 'chartjson-output.json')
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-bd319d25.406548626035855371/dashboard/pinpoint/models/quest/read_value.py", line 298, in _RetrieveOutputJson
    raise ReadValueError("The test didn't produce %s." % filename)
ReadValueError: The test didn't produce chartjson-output.json.
```

@perezju @eakuefner

**Comment by eakuefner** [comment]
Ah, so to be clear, what's happening here is that the file has also been renamed to `perftest-output.json`. So yes, pass `--isolated-script-test-perf-output`, but also, look for this filename instead.

**Comment by dave-2** [comment]
When I looked at the Swarming job, the output isolate had only `output.json` and no perf results.

The filename is not hard-coded, but rather it uses the value of that flag, right? So yes, we'd need to change both the flag's value and the filename that we look for.
