### ISSUE TITLE
Pinpoint - 500 error on results2

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4179]
If you try to acess the analyze benchmark results link from a failed Pinpoint job, you'll get a 500 error. Ie. https://pinpoint-dot-chromeperf.appspot.com/job/14c37b28840000

```
list index out of range (/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py:1553)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-cdde5128.407057111577072922/dashboard/pinpoint/handlers/results2.py", line 29, in get
    histogram_dicts = _FetchHistogramsDataFromJobData(job_data)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-cdde5128.407057111577072922/dashboard/pinpoint/handlers/results2.py", line 70, in _FetchHistogramsDataFromJobData
    result_arguments = executions[test_index].get('result_arguments', {})
IndexError: list index out of range
```

@dave-2

**Comment by dave-2** [comment]
It's because it's looking for an execution that doesn't exist. Since the build failed, there's no corresponding test execution.
