### ISSUE TITLE
[📍] Deadline exceeded while posting bug comment

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4221]
https://pinpoint-dot-chromeperf.appspot.com/job/12f61716840000
I'll probably just increase the timeout. It's 10s right now.

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/dashboard/pinpoint/models/job.py", line 226, in Run
    self._Complete()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/dashboard/pinpoint/models/job.py", line 149, in _Complete
    self._PostBugComment('\n'.join((title, self.url)))
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/dashboard/pinpoint/models/job.py", line 258, in _PostBugComment
    issue_tracker.AddBugComment(self.bug_id, *args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/dashboard/services/issue_tracker_service.py", line 82, in AddBugComment
    return self._MakeCommentRequest(bug_id, body, send_email=send_email)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/dashboard/services/issue_tracker_service.py", line 113, in _MakeCommentRequest
    if self._ExecuteRequest(request, ignore_error=False):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/dashboard/services/issue_tracker_service.py", line 260, in _ExecuteRequest
    response = request.execute()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/oauth2client/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/apiclient/googleapiclient/http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/oauth2client/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/oauth2client/oauth2client/client.py", line 563, in new_request
    redirections, connection_type)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/httplib2/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/httplib2/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-30cfa7e1.407334664967293829/httplib2/httplib2/__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/gae_override/httplib.py", line 526, in getresponse
    raise HTTPException(str(e))
HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues/794302/comments?alt=json&sendEmail=true
```

**Comment by dave-2** [comment]
Timeout was increased in https://chromium-review.googlesource.com/920796
