### ISSUE TITLE
[📍] 'DiagnosticRef' error while reading traces from histograms

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4243]
https://pinpoint-dot-chromeperf.appspot.com/job/12cdcce5840000
https://pinpoint-dot-chromeperf.appspot.com/job/14bbb385840000

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-c47e84b7.407366435166996267/dashboard/pinpoint/models/job.py", line 221, in Run
    work_left = self.state.ScheduleWork()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-c47e84b7.407366435166996267/dashboard/pinpoint/models/job.py", line 351, in ScheduleWork
    attempt.ScheduleWork()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-c47e84b7.407366435166996267/dashboard/pinpoint/models/attempt.py", line 65, in ScheduleWork
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-c47e84b7.407366435166996267/dashboard/pinpoint/models/attempt.py", line 69, in _Poll
    self._last_execution.Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-c47e84b7.407366435166996267/dashboard/pinpoint/models/quest/execution.py", line 99, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-c47e84b7.407366435166996267/dashboard/pinpoint/models/quest/read_value.py", line 227, in _Poll
    unique_trace_urls.update(trace_urls)
TypeError: 'DiagnosticRef' object is not iterable
```

**Comment by dave-2** [comment]
@simonhatch @eakuefner

**Comment by chiniforooshan** [comment]
Another example: https://pinpoint-dot-chromeperf.appspot.com/job/11805cf1840000

**Comment by dave-2** [comment]
Being tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=811332

**Comment by dave-2** [comment]
Sounds like that's the best we can do.
