### ISSUE TITLE
v8.browsing_desktop causes error in add_reserved_diagnostics

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4295]
@simonhatch noticed this yesterday. Stack trace from my machine:

```
Traceback (most recent call last):
  File "bin/add_reserved_diagnostics", line 94, in <module>
    sys.exit(main())
  File "bin/add_reserved_diagnostics", line 59, in main
    'name',))
  File "/work/code/catapult/tracing/tracing/value/merge_histograms.py", line 29, in MergeHistograms
    js_args=[os.path.abspath(json_path)] + list(groupby))
  File "/work/code/catapult/third_party/vinn/vinn/_vinn.py", line 188, in RunFile
    return _RunFileWithD8(temp_boostrap_file, js_args, v8_args, stdout, stdin)
  File "/work/code/catapult/third_party/vinn/vinn/_vinn.py", line 267, in _RunFileWithD8
    'Exception raised when executing %s:\n%s' % (js_file_path, out))
RuntimeError: Exception raised when executing /tmp/tmpuj4flA/_tmp_boostrap.js:
/tracing/value/diagnostics/generic_set.html:22: TypeError: Cannot convert undefined or null to object
    if (!(obj instanceof Array)) replacer = Object.keys(obj).sort();
                                                   ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at stableStringify (/tracing/value/diagnostics/generic_set.html:22:52)
    at GenericSet.addDiagnostic (/tracing/value/diagnostics/generic_set.html:93:19)
    at Map.addDiagnostics (/tracing/value/diagnostics/diagnostic_map.html:140:24)
    at Histogram.addHistogram (/tracing/value/histogram.html:593:24)
    at mergeLeafHistograms (/work/code/catapult/tracing/tracing/value/merge_histograms_cmdline.html:50:19)
    at mergeHistograms (/work/code/catapult/tracing/tracing/value/merge_histograms_cmdline.html:77:3)
    at eval (/work/code/catapult/tracing/tracing/value/merge_histograms_cmdline.html:85:28)
    at Object.loadHTMLFile (/work/code/catapult/third_party/vinn/vinn/html_imports_loader.js:140:5)
    at /work/code/catapult/third_party/vinn/vinn/d8_bootstrap.js:151:19
```

**Comment by benshayden** [comment]
Oh, javascript. Apparently, `typeof null === 'object'`. Maybe change this condition?
```
if (!(obj instanceof Array) && (obj !== null)) {
  replacer = Object.keys(obj).sort();
}
```

**Comment by eakuefner** [comment]
Heh, thanks @benshayden. Will do that, and will also fix Telemetry not to populate b_d if it doesn't need to be.
