### ISSUE TITLE
Pinpoint - Flakey test pinpoint.handlers.jobs_test.JobsTest.testGet_WithUser

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4363]
This seems to fail every once in a while

[752/1141] pinpoint.handlers.jobs_test.JobsTest.testGet_WithUser failed unexpectedly:
  Traceback (most recent call last):
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\third_party\mock\mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "C:\b\build\slave\Catapult_Windows_Tryserver\build\catapult\dashboard\dashboard\pinpoint\handlers\jobs_test.py", line 62, in testGet_WithUser
      self.assertEqual(job.AsDict([job_module.OPTION_STATE]), data['jobs'][0])
  AssertionError: {'status': 'Completed', 'auto_explore': True, 'updated': '2018-03-26T19:10:49.77 [truncated]... != {u'status': u'Completed', u'auto_explore': True, u'updated': u'2018-03-26T19:10: [truncated]...
  Diff is 881 characters long. Set self.maxDiff to None to see it.

**Comment by simonhatch** [comment]
Seems to only happen on windows, think we just need to sort the data to ensure we're looking at the same job.
