### ISSUE TITLE
Dashboard - Failing email_sheriff_test.EmailSheriffTest.testEmailSheriff_ContentAndRecipientAreCorrect

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4400]
[478/1132] email_sheriff_test.EmailSheriffTest.testEmailSheriff_ContentAndRecipientAreCorrect failed unexpectedly:
  Traceback (most recent call last):
    File "/b/build/slave/Catapult_Mac_Tryserver/build/catapult/third_party/mock/mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "/b/build/slave/Catapult_Mac_Tryserver/build/catapult/dashboard/dashboard/email_sheriff_test.py", line 69, in testEmailSheriff_ContentAndRecipientAreCorrect
      'perf-sheriff-group@google.com,sullivan@google.com', messages[0].to)
  AssertionError: 'perf-sheriff-group@google.com,sullivan@google.com' != u'perf-sheriff-group@google.com, sullivan@google.com'
[479/1132] email_sheriff_test.EmailSheriffTest.testEmailSheriff_MultipleSheriffs_AllGetEmailed failed unexpectedly:
  Traceback (most recent call last):
    File "/b/build/slave/Catapult_Mac_Tryserver/build/catapult/third_party/mock/mock.py", line 1201, in patched
      return func(*args, **keywargs)
    File "/b/build/slave/Catapult_Mac_Tryserver/build/catapult/dashboard/dashboard/email_sheriff_test.py", line 103, in testEmailSheriff_MultipleSheriffs_AllGetEmailed
      messages[0].to)
  AssertionError: 'perf-sheriff-group@google.com,sonnyrao@google.com,digit@google.com' != u'perf-sheriff-group@google.com, sonnyrao@google.com, digit@google.com'

Seeing a lot of these failures on the cq bots, wonder if we have a flakey test?

@eakuefner @anniesullie

**Comment by simonhatch** [comment]
This was actually fixed by https://chromium-review.googlesource.com/c/catapult/+/1010403, specified the wrong github # in there.

Although the greater problem of the underlying cause of these racy tests is still around.
