### ISSUE TITLE
No file to download from cloud storage for clear_system_cache on platform linux_mips64

### ISSUE THREAD

**Issue by ClarkWang-2013** [catapult-project/catapult#4430]
When running script in chromium on Loongson platform(mips64el):
$ tools/perf/run_benchmark --browser=release startup.cold.blank_page
`[ RUN      ] blank_page.html
(ERROR) 2018-01-03 15:22:35,733 browser.__init__:65  Failure while starting browser backend.
Traceback (most recent call last):
  File "/home/loongson/work/chrome60/third_party/catapult/telemetry/telemetry/internal/browser/browser.py", line 48, in __init__
    self._browser_backend.profile_directory)
  File "/home/loongson/work/chrome60/third_party/catapult/telemetry/telemetry/core/platform.py", line 186, in FlushSystemCacheForDirectory
    return self._platform_backend.FlushSystemCacheForDirectory(directory)
  File "/home/loongson/work/chrome60/third_party/catapult/telemetry/telemetry/internal/platform/desktop_platform_backend.py", line 21, in FlushSystemCacheForDirectory
    'clear_system_cache', self.GetArchName(), self.GetOSName())
  File "/home/loongson/work/chrome60/third_party/catapult/telemetry/telemetry/internal/util/binary_manager.py", line 63, in FetchPath
    return _binary_manager.FetchPath(binary_name, os_name, arch, os_version)
  File "/home/loongson/work/chrome60/third_party/catapult/common/py_utils/py_utils/binary_manager.py", line 38, in FetchPath
    os_version)
  File "/home/loongson/work/chrome60/third_party/catapult/common/py_utils/py_utils/binary_manager.py", line 60, in _WrapDependencyManagerFunction
    return function(binary_name, platform)
  File "/home/loongson/work/chrome60/third_party/catapult/dependency_manager/dependency_manager/manager.py", line 130, in FetchPath
    path, _ = self.FetchPathWithVersion(dependency, platform)
  File "/home/loongson/work/chrome60/third_party/catapult/dependency_manager/dependency_manager/manager.py", line 89, in FetchPathWithVersion
    raise exceptions.NoPathFoundError(dependency, platform)
NoPathFoundError: No file could be found locally, and no file to download from cloud storage for clear_system_cache on platform linux_mips64
`

**Comment by ClarkWang-2013** [comment]
I can build clear_system_cache in chromium:
$ ninja -C out/Rlease clear_system_cache

but I didn't know how to put clear_system_cache to cloud storage, and download by running telemetry.
