### ISSUE TITLE
[📍] Can't bisect into runtime call stats data

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#4439]
Example: https://pinpoint-dot-chromeperf.appspot.com/job/149e7937c40000

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-848976aa.409559211621551374/dashboard/pinpoint/models/quest/execution.py", line 98, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-848976aa.409559211621551374/dashboard/pinpoint/models/quest/read_value.py", line 160, in _Poll
    raise ReadValueError('Could not find values matching: %s' % name)
ReadValueError: Could not find values matching: histogram: GC:duration story: cold
```

From the [graphs](https://chromeperf.appspot.com/group_report?bug_id=840700)  the metric label indicates "GC:duration_avg / cold" but pinpoint seems to look for GC:duration only.

**Comment by simonhatch** [comment]
Re: the difference in names, the name in the histogram data is likely simply "GC:duration" with a "cold" story and use the "avg" statistic from that

Will have to dig into why the histogram output doesn't have that histogram though.

@dave-2

**Comment by dave-2** [comment]
I think this is the same as #4500. Duping onto that.
