### ISSUE TITLE
[📍] isolatedserver must be valid HTTPS URL, not chrome-isolated.appspot.com

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#4534]
ALL Pinpoint jobs are failing with this error.

Looks like it's caused by https://chromium-review.googlesource.com/c/chromium/tools/build/+/1124780 from this morning. It sets the isolate server to `chrome-isolated.appspot.com`. Pinpoint passes the isolate server from the builder to Swarming, and Swarming doesn't like the format. It requires `https://`.

@ehanley324 @nedn @simonhatch 

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-7cd8d0be.410725196081523019/dashboard/pinpoint/models/quest/execution.py", line 96, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-7cd8d0be.410725196081523019/dashboard/pinpoint/models/quest/run_test.py", line 191, in _Poll
    self._StartTask()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-7cd8d0be.410725196081523019/dashboard/pinpoint/models/quest/run_test.py", line 283, in _StartTask
    response = swarming.Swarming(self._swarming_server).Tasks().New(body)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-7cd8d0be.410725196081523019/dashboard/services/swarming.py", line 126, in New
    return request.RequestJson(url, method='POST', body=body)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-7cd8d0be.410725196081523019/dashboard/services/request.py", line 31, in RequestJson
    content = Request(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-7cd8d0be.410725196081523019/dashboard/services/request.py", line 86, in Request
    content = _RequestAndProcessHttpErrors(url, use_auth, scope, **kwargs)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-7cd8d0be.410725196081523019/dashboard/services/request.py", line 112, in _RequestAndProcessHttpErrors
    'HTTP status code %s: %s' % (response['status'], content))
HTTPException: HTTP status code 400: {"error": {"message": "isolatedserver must be valid HTTPS URL, not chrome-isolated.appspot.com"}}
```

**Comment by dave-2** [comment]
@martiniss

**Comment by dave-2** [comment]
I've patched `https://` in to the Chromium perf recipe: https://chromium-review.googlesource.com/c/chromium/tools/build/+/1125514.
Now I need to migrate the isolate data over to the correct URL.

**Comment by dave-2** [comment]
I think that would be useful! We do catch most of these kinds of things within one day, maybe we want it to run every hour?

Let me file a bug.

**Comment by dave-2** [comment]
Isolate data migration is in progress. It'll probably be done sometime tomorrow.

**Comment by dave-2** [comment]
Data migration is done!
