### ISSUE TITLE
[📍] Perf job failing with ReadValueError

### ISSUE THREAD

**Issue by amyqiu** [catapult-project/catapult#4537]
As seen here: https://pinpoint-dot-chromeperf.appspot.com/job/1282bac4a40000

Running this benchmark (rendering.desktop) on Windows 10 leads to the following error every time:

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-82213060.410908204752561634/dashboard/pinpoint/models/quest/execution.py", line 95, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-82213060.410908204752561634/dashboard/pinpoint/models/quest/read_value.py", line 103, in _Poll
    self._isolate_server, self._isolate_hash, self._results_filename)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-82213060.410908204752561634/dashboard/pinpoint/models/quest/read_value.py", line 261, in _RetrieveOutputJson
    raise ReadValueError("The test didn't produce %s." % filename)
ReadValueError: The test didn't produce rendering.desktop/perf_results.json.
```

The benchmark runs successfully on other platforms:
https://pinpoint-dot-chromeperf.appspot.com/job/14db417aa40000
https://pinpoint-dot-chromeperf.appspot.com/job/12f6a44ca40000

**Comment by simonhatch** [comment]
@dave-2

**Comment by dave-2** [comment]
Looks like the path separators are different on Windows compared with other platforms.

Filed [chromium:861856](https://bugs.chromium.org/p/chromium/issues/detail?id=861856) to see if Infra>Platforms wants to fix it on the infra side, and uploaded a [workaround](https://chromium-review.googlesource.com/c/catapult/+/1129634) in Pinpoint as well.
