### ISSUE TITLE
[📍] 'Shard indicators must be present for perf tests'

### ISSUE THREAD

**Issue by alculquicondor** [catapult-project/catapult#4538]
Job link: https://pinpoint-dot-chromeperf.appspot.com/job/16bb2270a40000

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-82213060.410908204752561634/dashboard/pinpoint/models/quest/execution.py", line 95, in Poll
    self._Poll()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-82213060.410908204752561634/dashboard/pinpoint/models/quest/run_test.py", line 220, in _Poll
    'message was:\n%s' % exception_string)
SwarmingTestError: The test failed. The test's error message was:
Exception: Shard indicators must be present for perf tests
```

**Comment by simonhatch** [comment]
@dave-2

**Comment by alculquicondor** [comment]
This is still happening, any idea why? Is it a usage error?

**Comment by dave-2** [comment]
Fix is in code review! https://chromium-review.googlesource.com/c/catapult/+/1130950
