### ISSUE TITLE
soundwave: pinpoint-cli crashes for windows bots

### ISSUE THREAD

**Issue by sadrulhc** [catapult-project/catapult#4594]
Trying to get csv results for rendering.desktop bots fails with the following:

Traceback (most recent call last):
  File "./experimental/soundwave/bin/pinpoint_cli", line 72, in <module>
    sys.exit(main())
  File "./experimental/soundwave/bin/pinpoint_cli", line 56, in main
    return commands.DownloadJobResultsAsCsv(api, args.job_ids, args.output)
  File "experimental/soundwave/pinpoint_cli/commands.py", line 28, in DownloadJobResultsAsCsv
    histograms = api.isolate.RetrieveFile(isolate_hash, results_file)
  File "experimental/soundwave/services/isolate_service.py", line 37, in RetrieveFile
    return self.Retrieve(container['files'][filename]['h'])
KeyError: u'rendering.desktop/perf_results.json'

@perezju

**Comment by perezju** [comment]
Yes, it's because of this [TODO](https://cs.chromium.org/chromium/src/third_party/catapult/experimental/soundwave/pinpoint_cli/commands.py?rcl=237fb2a03b4b525d829b169d7061b79917262797&l=21). :stuck_out_tongue: 

I'll send out a CL to fix this. Thanks for using pinpoint_cli!
