### ISSUE TITLE
PathMissingError: Unable to find apk specified by --webview-embedder-apk=None

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#4602]
From my failed pinpoint job (https://pinpoint-dot-chromeperf.appspot.com/job/14a13aade40000):

Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-9662809a.413644294060734375/dashboard/pinpoint/models/job.py", line 350, in Run
    work_left = self.state.ScheduleWork()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-9662809a.413644294060734375/dashboard/pinpoint/models/job_state.py", line 139, in ScheduleWork
    self._RaiseErrorIfAllAttemptsFailed()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-9662809a.413644294060734375/dashboard/pinpoint/models/job_state.py", line 159, in _RaiseErrorIfAllAttemptsFailed
    'was:\n%s' % (exception_count, attempt_count, exception))
Exception: All of the runs failed. The most common error (20/20 runs) was:
PathMissingError: Unable to find apk specified by --webview-embedder-apk=None

@dave-2

**Comment by chiniforooshan** [comment]
crbug.com/903811
